### PR TITLE
protoc-gen-swagger: Fix formatting of license field definition.

### PR DESCRIPTION
**Pull request by ivucica**

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Looks like we need to regenerate the protofile as well - not sure where the hash comes from but there it is. https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md#i-want-to-regenerate-the-files-after-making-changes

**Comment by ivucica** [comment]
It's so very strange that touching just the whitespace causes this.

I can't do this straight away unfortunately.

**Comment by johanbrandhorst** [comment]
I can force push a change, leave it to me.

**Comment by ivucica** [comment]
If you feel like it, sure, but this is really a nit anyway :-)

**Comment by johanbrandhorst** [comment]
Files regenerated.

**Pull request merged**
