### PR TITLE
Add new option for the decoder - to disallow unknown fields

### PR DESCRIPTION
**Pull request by vsaveliev**
Hi, gRPC Gateway's Team.

It's a copy of https://github.com/grpc-ecosystem/grpc-gateway/pull/948.

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Could you please rebase on master to fix the bazel error?

**Comment by vsaveliev** [comment]
done.

**Comment by johanbrandhorst** [comment]
Thanks for your contribution!

**Comment by vsaveliev** [comment]
Thank you for the review and help!

**Pull request merged**
