### PR TITLE
Add go mod file

### PR DESCRIPTION
**Pull request by kasuboski**
This just adds a go.mod file at the project root as discussed in #755

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
@kasuboski Thanks for your contribution! I think we want to remove the old `Gopkg.toml` and `Gopkg.lock` files at the same time. Also we may be able to get rid of some more files, @achew22 I think you had some input here.

**Comment by johanbrandhorst** [comment]
Please rebase on master for new CI functionality.

**Comment by Everlag** [comment]
This would be very useful for us, is there an ETA on this being merged?

**Comment by johanbrandhorst** [comment]
@Everlag please open a separate PR, it seems like @kasuboski has abandoned this.

**Comment by Everlag** [comment]
Will do. I don't have the bandwidth at the moment but have set aside some time next week.

**Comment by johanbrandhorst** [comment]
Closing as this appears abandoned

**Pull request closed without merging**
