### PR TITLE
Pr issue template v2

### PR DESCRIPTION
**Pull request by iamrajiv**
#### References to other Issues or PRs
#1366 

removed Issue template from `_docs` and made issue and PR template in `.github` of v2 branch of grpc-gateway

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
I think you need to rebase on v2

**Comment by iamrajiv** [comment]
hey @johanbrandhorst can you help me why one test is not passing?

**Comment by johanbrandhorst** [comment]
> hey @johanbrandhorst can you help me why one test is not passing?

I'm pretty sure it's because you need to rebase your branch on top of  `v2`:
```shell 
$ git pull --rebase origin v2
```
Should do it.

**Comment by iamrajiv** [comment]
@johanbrandhorst I am closing this PR because of conflict. I have made a new PR #1371

**Pull request closed without merging**
