### PR TITLE
Supports oneof fields in more places

### LINKED ISSUE #413: oneof fields are not supported as the "body"?
Hi,

Here's a short sample of proto input:
```protobuf
syntax = "proto3";

package foo;

import "google/api/annotations.proto";
import "google/protobuf/struct.proto";

service FooService {
  rpc foo(FooRequest) returns (FooResponse) {
    option (google.api.http) = {
      post: "/foo-message"
      body: "msg"
      additional_bindings: {
        post: "/foo-struct"
        body: "str"
      };
    };
  }
}

message FooRequest {
  oneof payload {
    string msg = 1;
    google.protobuf.Struct str = 2;
  }
}

message FooResponse {}
```

It successfully generates the `pb.gw.go` file, but `go build` fails as:
```
./foo.pb.gw.go:40: protoReq.Msg undefined (type FooRequest has no field or method Msg)
./foo.pb.gw.go:61: protoReq.Str undefined (type FooRequest has no field or method Str)
```

The related line looks like:
```go
if err := marshaler.NewDecoder(req.Body).Decode(&protoReq.Msg); err != nil {
```

The generated go type has the name of field as `Payload` (the name of oneof) rather than individual oneof names, and that field accepts `FooRequest_Msg` or `FooRequest_Str` type. Maybe the codegen can't deal with oneof fields in the body parameter?

### PR DESCRIPTION
**Pull request by yugui**
* root of the request body: fixes #413 
* path parameters

### CODE REVIEW

**Comment by yugui** [comment]
I noticed that the alloc function does not work when the target message is defined outside of the current package. I'll rewrite this PR.

**Comment by mcos** [comment]
@yugui What's the current state of this?

**Comment by abronan** [comment]
Although it's relatively easy to find a workaround when in need of such a message structure, supporting `oneof` at the root of the request body would be awesome 🤗 

Is there any help needed to push this PR forward?

**Comment by tmc** [comment]
This is replaced by #634

**Pull request closed without merging**
