### PR TITLE
annotations: Sort import order.

### PR DESCRIPTION
**Pull request by someone1**
It inadvertently got caught in my proto file [linter](https://github.com/ckaznocha/protoc-gen-lint) script which checks against [Google's Proto Style Guide](https://developers.google.com/protocol-buffers/docs/style)

### CODE REVIEW

**Comment by someone1** [comment]
FYI - the `jfbrandhorst/grpc-gateway-build-env:1.13` image can't be pulled in a Windows docker environment and running it as described in the contributing doc errors with:

```bash
protoc -I /usr/local/bin//../include -I. -Ithird_party/googleapis --plugin=bin/protoc-gen-swagger --swagger_out=logtostderr=true,allow_repeated_fields_in_body=true,use_go_templates=true,Mgoogle/protobuf/field_mask.proto=google.golang.org/genproto/protobuf/field_mask,Mgoogle/protobuf/descriptor.proto=github.com/golang/protobuf/protoc-gen-go/descriptor,Mexamples/proto/sub/message.proto=github.com/grpc-ecosystem/grpc-gateway/examples/proto/sub,grpc_api_configuration=examples/proto/examplepb/unannotated_echo_service.yaml:. examples/proto/examplepb/echo_service.proto examples/proto/examplepb/a_bit_of_everything.proto examples/proto/examplepb/wrappers.proto examples/proto/examplepb/stream.proto examples/proto/examplepb/unannotated_echo_service.proto examples/proto/examplepb/use_go_template.proto examples/proto/examplepb/response_body_service.proto
generate -i examples/proto/examplepb/echo_service.swagger.json \
    -l go -o examples/clients/echo --additional-properties packageName=echo
make: generate: Command not found
make: *** [Makefile:169: examples/clients/echo/client.go] Error 127
```

**Comment by achew22** [comment]
@someone1, Thanks for sending in the patch! Every little bit helps us out.

WRT the issue you're having on windows building @johanbrandhorst's repo, could I have you open an issue there so it doesn't get lost?

Thanks again!

**Comment by someone1** [comment]
The Docker image seems to be generated from [this repo](https://github.com/grpc-ecosystem/grpc-gateway/tree/master/.circleci)? Should I open an issue here?

**Comment by johanbrandhorst** [comment]
@someone1 please raise a separate issue about the docker image. You did indeed find the source. I am out of the country at the moment but will have a look when I have time.

**Pull request merged**
