### PR TITLE
fix(protoc-gen-grpc-gateway): error if identical annotations are provided just in the same service

### LINKED ISSUE #2411: duplicate annotation error when the same endpoint is used by two different services
## 🐛 Bug Report
When two different services have the same endpoint annotation, is not possible to generate the protogen files

## To Reproduce
service.proto file
```
service MyServiceNumberOne {
  rpc GetHealth(GetHealthRequest) returns (GetHealthResponse) {
    option (google.api.http) = {
      get : "/api/v1/health"
    };
  }
}

service MyServiceNumberTwo {
  rpc GetHealth(GetHealthRequest) returns (GetHealthResponse) {
    option (google.api.http) = {
      get : "/api/v1/health"
    };
  }
}

message GetHealthRequest {}
message GetHealthResponse {}
```

## Expected behavior
The expected behavior would be to generate the protogen files without error

## Actual Behavior
```
Failure: failed to map insertion points: unexpected response error: duplicate annotation: method=GET, template=/api/v1/health.
```

## Your Environment
go 1.17
grpc-gateway 2.6.0

## Aditional information
Searching about this error, I found this [issue](https://github.com/grpc-ecosystem/grpc-gateway/issues/1865) that might be the reason for this behavior, but I'm not sure about it.

### PR DESCRIPTION
**Pull request by aronrichter**
#### References to other Issues or PRs
fixes #2411 

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?
yess 😁 

#### Brief description of what is fixed or changed
add the `Service` in the struct `annotationIdentifier`, so when `CheckDuplicateAnnotation` method is called, it only returns an error if the duplicated annotation exists in the same service

#### Other comments
No further comments

### CODE REVIEW

**Comment by aronrichter** [comment]
@googlebot I signed it!

**Review by johanbrandhorst — APPROVED** [review]
LGTM

**Comment by johanbrandhorst** [comment]
@googlebot I consent.

**Comment by johanbrandhorst** [comment]
Thanks for your contribution!

**Pull request merged**
