### PR TITLE
Generate shorter description names for swagger output.

### PR DESCRIPTION
**Pull request by achew22**

### CODE REVIEW

**Comment by yugui** [comment]
Let me confirm.  Why is the shorter name better than the current name?
I am worrying about if it causes name conflicts because request/response types for a service can come from several packages.

**Comment by t-yuki** [comment]
swagger-ui and swagger-editor uses the name as a schema name in UI
http://petstore.swagger.io/?url=https://raw.githubusercontent.com/gengo/grpc-gateway/master/examples/examplepb/streamless_everything.swagger.json#!/ABitOfEverythingService/List
http://editor.swagger.io/

**Comment by yugui** [comment]
@t-yuki Thank you.  But I don't think it justifies the change if the change causes name conflicts.

**Comment by tmc** [comment]
Maybe it'd be nice if types were prefixed if they aren't defined in the proto file(s) that are being used to render the swagger output.

**Comment by achew22** [comment]
@yugui I was very careful to make sure that it wouldn't cause name conflicts. I believe that the test cases demonstrate that. The thing I dislike about this patch is that you were iterating on your API you might create a new Foo proto when you have a preexisting one. That would change the name of both protos to be unique but break your preexisting code.

I figured I would write this up and just see what people thought about it. Doesn't have to go in

**Comment by achew22** [comment]
I switched to doing it your way Yugui and I'm much happier. Thanks!

**Pull request closed without merging**
