### PR TITLE
Add proto marshaller for proto-over-http

### PR DESCRIPTION
**Pull request by MatthewDolan**

### CODE REVIEW

**Comment by tmc** [comment]
Thanks for your contribution! master has a build system fix, can you please rebase this?

**Comment by MatthewDolan** [comment]
@tmc thanks.

The build is passing now.

**Comment by MatthewDolan** [comment]
@tmc Is there anything else I need to do here?

**Comment by Mistobaan** [comment]
This seems interesting. Any more context / documentation on how to use it from a frontend?

**Comment by MatthewDolan** [comment]
Once the `ProtoMarshaller` is added as a marshaller on the server side, you can do "proto over http." The client can send an http request with a content type "application/octet-stream" where the body is a serialized proto and the gateway will be able to handle that.

**Pull request merged**
