### PR TITLE
mux: fix path components mutation

### LINKED ISSUE #2990: Unexpected route with verb pattern
## 🐛 Bug Report

Assume there are three handler patterns as follows:

1. `POST /api/v1/organizations:verb`
2. `POST /api/v1/organizations`
3. `POST /api/v1/dummies:verb`

Request to `POST /api/v1/organizations:verb` but it routes to the unexpected handler which handles the pattern for `POST /api/v1/organizations`.

## To Reproduce

By extending the `TestMuxServeHTTP` test with the following test cases:

```go
		{
			patterns: []stubPattern{
				{
					method: "POST",
					ops: []int{
						int(utilities.OpLitPush), 0,
						int(utilities.OpLitPush), 1,
						int(utilities.OpLitPush), 2,
					},
					pool: []string{"api", "v1", "organizations"},
					verb: "verb",
				},
				{
					method: "POST",
					ops: []int{
						int(utilities.OpLitPush), 0,
						int(utilities.OpLitPush), 1,
						int(utilities.OpLitPush), 2,
					},
					pool: []string{"api", "v1", "organizations"},
					verb: "",
				},
				{
					method: "POST",
					ops: []int{
						int(utilities.OpLitPush), 0,
						int(utilities.OpLitPush), 1,
						int(utilities.OpLitPush), 2,
					},
					pool: []string{"api", "v1", "dummies"},
					verb: "verb",
				},
			},
			reqMethod: "POST",
			reqPath:   "/api/v1/organizations:verb",
			headers: map[string]string{
				"Content-Type": "application/json",
			},
			respStatus:     http.StatusOK,
			unescapingMode: runtime.UnescapingModeAllCharacters,
			respContent:    "POST /api/v1/organizations:verb",
		},
```

Output:

```
=== RUN   TestMuxServeHTTP/0
    mux_test.go:115: w.Body = "POST /api/v1/organizations"; want "POST /api/v1/organizations:verb"; patterns=[{POST [2 0 2 1 2 2] [api v1 organizations] verb} {POST [2 0 2 1 2 2] [api v1 organizations] } {POST [2 0 2 1 2 2] [api v1 dummies] verb}]; req=&{POST https://host.example/api/v1/organizations:verb HTTP/1.1 1 1 map[Content-Type:[application/json]] {} 0x1046b2fc0 0 [] false host.example map[] map[] <nil> map[]   <nil> <nil> <nil> 0x14000026108}
--- FAIL: TestMuxServeHTTP (0.00s)
    --- FAIL: TestMuxServeHTTP/0 (0.00s)
FAIL
```

## Expected behavior

Route to `POST /api/v1/organizations:verb`

## Actual Behavior

Route to `POST /api/v1/organizations`

## Your Environment

- `v2.12.0`
- `v2.13.0`

### PR DESCRIPTION
**Pull request by jonathaningram**
#### References to other Issues or PRs

Fixes #2990

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?

Yes

#### Brief description of what is fixed or changed

There's a for loop which looks at handlers that might match. However there's a case where the path components slice was mutated if idx > 0. Subsequent iterations of the for loop might end up with idx <= 0 and they'll be using a version of the path components that were mutated from the previous iteration. Instead, we keep a copy of the path components at the top, and inside each iteration we make a copy, then modify that.

### CODE REVIEW

**Comment by jonathaningram** [comment]
@cclien0725 @johanbrandhorst I believe this is the fix we need. If it looks good, you can just squash and merge it.

**Comment by johanbrandhorst** [comment]
Thanks for your contribution! @cclien0725 could you confirm that this fixes your issue?

**Comment by jonathaningram** [comment]
@johanbrandhorst yeah it's all a bit hard to understand. Not claiming I have an obvious better way of writing it without looking into it more, but agree that it's hairy.

Interestingly, by changing the code to NOT mutate data, we avoided a bug. Speaks to benefits of immutable data.

**Comment by cclien0725** [comment]
@jonathaningram @johanbrandhorst thanks for both of your help, this fixes the issue!

**Pull request merged**
