### PR TITLE
Update ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by prologic**
Fix minor typo

### CODE REVIEW

**Comment by srenatus** [comment]
💭 There's no _trivial fix_ exception from the CLA, is there?

**Comment by johanbrandhorst** [comment]
Nope, the CLA is mandatory :grimacing:.

**Comment by prologic** [comment]
Ooops I forgot to sign the CLA I mean to when I got home a few evenings ago. Done now! :D

**Comment by srenatus** [comment]
IIRC the CLA will never be checked again, though... @johanbrandhorst am I making this up?

**Comment by srenatus** [comment]
🤔 maybe I'm wrong: https://github.com/fastlane/fastlane/issues/11122?

**Comment by johanbrandhorst** [comment]
The bot will check the CLA again if the user addresses the bot I think. It's part of the CLA signing instructions.

**Comment by johanbrandhorst** [comment]
We can also manually override the CLA bot. @achew22.

**Comment by achew22** [comment]
I just retriggered the bot and it is happy now, but in the future (per the instructions from the bot):

> Once you've signed (or fixed any issues), please reply here with `@googlebot I signed it!`) and we'll verify it.

**Pull request merged**
