### PR TITLE
fix: remove `push_bsr_plugins` Github Action job

### LINKED ISSUE #3202: Github Action `push_bsr_plugins` is failing
## 🐛 Bug Report

The job [push_bsr_plugins](https://github.com/grpc-ecosystem/grpc-gateway/actions/runs/4246481305/jobs/7383348765#logs) is failing, I think it's due to the change in the URL path of the plugin from https://buf.build/grpc-ecosystem/grpc-gateway to https://buf.build/grpc-ecosystem/gateway.

I can't seem to find the documentation of how to push the plugin to buf.build , but I assume that we only need to do little adjustment to the `docker push` command.

In the meantime before this fixed, can you help by manually pushing the v2.15.1 to buf.build?

## To Reproduce

https://github.com/grpc-ecosystem/grpc-gateway/actions/runs/4246481305/jobs/7383348765#logs

## Expected behavior

The push to buf.build succeeds.

## Actual Behavior

```
Error: buildx failed with: ERROR: failed to solve: failed to push plugins.buf.build/grpc-ecosystem/grpc-gateway:v2.15.1-1: failed commit on ref "manifest-sha256:2b3a737a779e4f4a6e6746240c63c7c53904ad7275905d9866aa87c5b4581fa9": unexpected status: 400 Bad Request
```

### PR DESCRIPTION
**Pull request by gunturaf**
#### References to other Issues or PRs

Fixes #3202 

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/CONTRIBUTING.md)?

Yes.

#### Brief description of what is fixed or changed

- fix `tags` in `push_bsr_plugins` to point to the updated plugin name in buf.build.

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Hi, thanks for your contribution! I think we can just do away with this job altogether now, the Buf team is maintaining this plugin. It will be updated to v2.15.1 soon. If you want, you can repurpose this branch to delete both the plugin push jobs and the Dockerfiles.

**Review by johanbrandhorst — CHANGES_REQUESTED** [review]
Lets delete these instead

**Comment by gunturaf** [comment]
Alright, didn't know that fact before. I'll repurpose and rename the PR for that instead.

**Review by johanbrandhorst — APPROVED** [review]
LGTM

**Pull request merged**
