### PR TITLE
Rebase Feature/oneof opt body

### PR DESCRIPTION
**Pull request by Tommy-42**
a small rebase from master ( this one was really outdated )

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Hi @Tommy-42. It looks like something terrible has happened here. Are all these conflicts and changes really right?

**Comment by Tommy-42** [comment]
hi @johanbrandhorst , I may have done something wrong :/ 

I've forked the grpc-gateway, checkout the branch `feature/oneof-opt-body`.

the next thing i've done is  : `git rebase origin/master` to be able to get the last commit from the master branch

I've resolved some conflict and pushd. Am i missing something here ?  ( I am usually doing this to update an old branch )

**Comment by johanbrandhorst** [comment]
Yeah I don't know how you ended up in this state but that sounds about right.. maybe try a poor mans rebase and just copy the changes you _think_ it needs from the branch into a fresh branch? Don't worry about the generated changes since we can just regenerate the files.

**Comment by Tommy-42** [comment]
oh my ... I found out why ... I don't why I used `feature/oneof-opt-body` instead of `feature/oneof` ... I am going fix that. thanks

**Comment by Tommy-42** [comment]
I am going to close this one and reopen a new one when I will resolve the conflict

**Pull request closed without merging**
