### PR TITLE
fix slice appending in generating field mask paths

### LINKED ISSUE #1549: incorrect field mask generated for deeply nested struct
## 🐛 Bug Report

if an input json is deeply nested, the generated field mask may be incorrect.

input: `{"foo": {"bar": {"baz": {"a": 1, "b": 2}}}}`
expected field mask: `["foo.bar.baz.a", "foo.bar.baz.b"]`
got: `["foo.bar.baz.a", "foo.bar.baz.a"]`

## To Reproduce

add another test case in `runtime/fieldmask_test.go`.`TestFieldMaskFromRequestBody` before line 58:
`{name: "deep", input: `{"foo": {"bar": {"baz": {"a": 1, "b": 2}}}}`, expected: newFieldMask("foo.bar.baz.a", "foo.bar.baz.b")},`

it fails

## Expected behavior

two different paths in the field mask

## Actual Behavior

two same paths

## Your Environment
mac OSX
go 1.14.1
(Environment name, version and operating system.)

### PR DESCRIPTION
**Pull request by houz42**
Fixes #1549 

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?

yes

#### Brief description of what is fixed or changed
join field mask paths earlier in case slice appendings overwrite shared underlying array.

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Hey, looks like you need to rerun some of the bazel commands as well. See https://github.com/grpc-ecosystem/grpc-gateway/blob/v2/CONTRIBUTING.md#i-want-to-regenerate-the-files-after-making-changes.

**Comment by houz42** [comment]
@googlebot I consent

**Comment by houz42** [comment]
@johanbrandhorst done

**Comment by johanbrandhorst** [comment]
Thanks for your contribution!

**Pull request merged**
