### PR TITLE
typo in mux.go

### PR DESCRIPTION
**Pull request by gabroo**
#### Brief description of what is fixed or changed
typo in mux.go

### CODE REVIEW

**Review by johanbrandhorst — APPROVED** [review]
LGTM

**Comment by johanbrandhorst** [comment]
Thanks for your contribution, could you please make sure to sign the Google CLA and include a screenshot after you've completed it? We've had some problems with @google-cla recently. Here are the instructions: https://github.com/grpc-ecosystem/grpc-gateway/pull/2147#issuecomment-881573094.

**Comment by gabroo** [comment]
Seems like my GitHub account wasn't registered properly with @google email. Not sure if I can screenshot the corp website, but it says "All necessary CLAs are signed" with green checkmark. Can you check on your end if it's ok?

**Comment by johanbrandhorst** [comment]
Thanks for your contribution!

**Pull request merged**
