### PR TITLE
LICENSE.txt got 404 replace to LICENSE

### PR DESCRIPTION
**Pull request by yuta-hidaka**
#### References to other Issues or PRs

- LICENSE.txt was changed to LICENSE.
- And the documentation got 404 when I tried to refer.

#### Brief description of what is fixed or changed

- Replace link text LICENSE.txt to LICENSE.

### Summary by CodeRabbit

- Documentation: Updated URLs in README.md, docs/index.md, and various .proto files to correctly point to the LICENSE file instead of LICENSE.txt.
- Documentation: Enhanced explanations and examples in README.md for generating gRPC stubs, implementing services, generating reverse-proxies, and generating OpenAPI definitions.

### CODE REVIEW

**Review by johanbrandhorst — APPROVED** [review]
Thanks!

**Comment by johanbrandhorst** [comment]
Looks like there are some generation failures, see `CONTRIBUTING.md` for a guide on how to regenerate all the files.

**Review by johanbrandhorst — CHANGES_REQUESTED** [review]
Regenerate files

**Comment by yuta-hidaka** [comment]
@johanbrandhorst 

Sorry about that, I did regenerate files in this commit!

https://github.com/grpc-ecosystem/grpc-gateway/pull/3627/commits/5f6f0a3f6bf8f90904341810deabba15a9d66cb0

**Review by johanbrandhorst — APPROVED** [review]

**Pull request merged**
