### PR TITLE
Use collectionFormat multi for query params of repeated fields

### PR DESCRIPTION
**Pull request by bmperrea**
Solves #756 . Also formats `protoc-gen-swagger/genswagger/template_test.go` according to `go fmt`.

### CODE REVIEW

**Comment by achew22** [comment]
Looks like really great work! FYI, I think the way to fix the generate CI failure is to run

```
docker run -v $(pwd):/go/src/github.com/grpc-ecosystem/grpc-gateway --rm jfbrandhorst/grpc-gateway-build-env:1.12 \
    /bin/bash -c 'cd /go/src/github.com/grpc-ecosystem/grpc-gateway && \
        make realclean && \
        make examples SWAGGER_CODEGEN="${SWAGGER_CODEGEN}"'
```

which will regenerate the examples. I'm really looking forward to this!

**Comment by bmperrea** [comment]
Thanks @achew22 ! A docker run to generate these files will be great - I was having trouble figuring out how to get the right version of `swagger-codegen` (2.2.2).

When I run the command you posted I get
```
can't load package: package github.com/golang/protobuf/protoc-gen-go: cannot find package "github.com/golang/protobuf/protoc-gen-go" in any of:
	/usr/local/go/src/github.com/golang/protobuf/protoc-gen-go (from $GOROOT)
	/go/src/github.com/golang/protobuf/protoc-gen-go (from $GOPATH)
```
I have that installed on my local, but I guess the docker run is missing a dependency.

**Comment by johanbrandhorst** [comment]
That's very strange, this is the command run by CI when generating the diff that's failing. Are you sure you ran the command correctly?

**Comment by johanbrandhorst** [comment]
Ah, there is a problem with the mount path in Andrews link. Try this:
```
docker run -v $(pwd):/src/grpc-gateway --rm jfbrandhorst/grpc-gateway-build-env:1.12 \ /bin/bash -c 'cd /src/grpc-gateway && \         make realclean && \         make examples SWAGGER_CODEGEN="${SWAGGER_CODEGEN}"'
```

**Comment by johanbrandhorst** [comment]
FYI the source of truth for this command is CONTRIBUTING.md

**Comment by johanbrandhorst** [comment]
(Andrews command is how we used to run it before we switched to go modules).

**Comment by johanbrandhorst** [comment]
Note to self: tests are a bit flaky, we should consider increasing the wait for the server to start up.

**Comment by johanbrandhorst** [comment]
Thanks for your contribution!

**Comment by johanbrandhorst** [comment]
We should make a release with this new functionality

**Comment by mmarod** [comment]
I believe that this may have inadvertently broken spec...

```
  "definitions": {
    "Foo": {
      "type": "object",
      "properties": {
        "foo": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Bar"
          },
          "description": "foo",
          "collectionFormat": "multi"
        }
...
```

This spits out the following error when I run `swagger generate server`

```
- definitions.Foo.properties.foo.collectionFormat in body is a forbidden property
```

**Comment by johanbrandhorst** [comment]
Thanks for your report @mmarod, could you raise an issue please? That is unfortunate.

**Comment by johanbrandhorst** [comment]
My immediate thought is that is happens when we have repeated fields in the body of a request instead of in the query parameters of the URL. Might just need a little extra logic.

**Comment by johanbrandhorst** [comment]
I raised https://github.com/grpc-ecosystem/grpc-gateway/issues/906

**Comment by c2nc** [comment]
I have same trouble when do swagger spec validation...
Fix please guys. Thanks

Look here
https://github.com/OAI/OpenAPI-Specification/issues/419#issuecomment-128788426

**Comment by johanbrandhorst** [comment]
Since that makes two of you that have spoken up I'm going to revert this until we can fix #906 at the same time.

**Comment by johanbrandhorst** [comment]
I've reverted the change in master and will make another release.

**Pull request merged**
