### PR TITLE
runtime/handler: Support conditional Flush via header. (#435)

### PR DESCRIPTION
**Pull request by hexfusion**
* Support conditionally disabling manual Flush via header key, falling back to internal net/http handling. "flush after chunk"

If this idea makes sense I will add tests.

### CODE REVIEW

**Comment by tmc** [comment]
Can you describe your use case?

The current check for simple lack of presence probably should be a little more strict, additionally this would need tests and documentation to be accepted.

**Comment by hexfusion** [comment]
@tmc understood, I will get this hammered down and include tests. Thanks!

**Comment by hexfusion** [comment]
@googlebot I signed it!

**Comment by hexfusion** [comment]
Closing this for now while I rethink approach.

**Pull request closed without merging**
