### PR TITLE
Error on nested namespacing collisions for message

### PR DESCRIPTION
**Pull request by johnchildren**
Nested messages can currently have name collisions with un-nested
messages, this commit adds an error if a collision occurs, though
hopefully this should be a reasonably rare occurrence.

In the case of a message Bar with a nested field Foo colliding with a
message BarFoo the error message will look like:

```
<input>:1:1:protoc-gen-swagger: message schema name collision: testBarFoo would be defined twice due to message nesting
```

It is possible there may be other causes for collision but I am
reasonably sure this is the only way it can happen without a failure in
protoc first.

### CODE REVIEW

**Comment by johnchildren** [comment]
Should prevent https://github.com/grpc-ecosystem/grpc-gateway/issues/1066 from occuring

**Comment by johanbrandhorst** [comment]
Thanks for the contribution! Have you tested this branch against your error reproduction case?

**Comment by johnchildren** [comment]
Yes! The error message in the config is actually from my reproduction case (slightly modified).

However it looks like some of the projects test cases would fail if this change was added so I will have to revise it.

**Comment by johnchildren** [comment]
Trying to figure out why this is failing and I'm not sure, but it may be that there are cases where a definition is passed into this function twice, perhaps when a file is imported twice? Anyway I think perhaps there isn't a way for me to resolve this easily so would recommend closing this PR and reconsidering.

It may be that the only real solution is to add a delimiter unavailable in protobuf message names to the FQMN, but this would be a big breaking change and may break a lot of people's APIs. Alternatively this error could be downgraded to just a warning?

**Pull request closed without merging**
