### PR TITLE
Add request_context flag to utilize (*http.Request).Context() in handlers

### PR DESCRIPTION
**Pull request by tmc**
This is a simplification of #251.

This PR adds the request_context flag which when true will utilize the incoming *http.Request's context when invoking grpc methods.

### CODE REVIEW

**Comment by tmc** [comment]
(dummy comment to trigger cla/google)

**Comment by tmc** [comment]
@kokaz can you comment here to pass the cla bot?

**Comment by kokaz** [comment]
I agreed to the CLA @googlebot

**Comment by tmc** [comment]
Thanks @kokaz -- I want one more LGTM from another maintainer before merging. ping @yugui @kazegusuri @achew22 @t-yuki

**Comment by achew22** [comment]
Is there a strategy for making this the default in the future or will it remain an optional feature?

Should we have a generated example with this turned on?

**Comment by tmc** [comment]
I think this should become the default once we're okay with degrading 1.6 support.
I added testing this code path to the travisci configuration, I'm not certain adding a generated example provides that much value.

**Comment by kokaz** [comment]
Is there any progress on that?

**Comment by AmandaCameron** [comment]
Any chance on getting this merged sometime soon? It'd be very helpful with stuff such as routing tracing through the grpc-gateway to the backend grpc service.

**Comment by achew22** [comment]
@tmc what information are you trying to get out of the HTTP request context that isn't available now?

**Comment by tmc** [comment]
@achew22 i think a pretty good use-case is tracing (opentracing or google cloud trace)

**Comment by AmandaCameron** [comment]
Tracing is what my usecase is for this PR. It's easier to thread the nessary tracing information through a http middleware instead of a grpc serverinterceptor, and more clean, I feel. It'd also allow middleware to do whatever other context manupulation it wants.

**Pull request merged**
