### PR TITLE
[WIP] Support oneof fields in body

### LINKED ISSUE #413: oneof fields are not supported as the "body"?
Hi,

Here's a short sample of proto input:
```protobuf
syntax = "proto3";

package foo;

import "google/api/annotations.proto";
import "google/protobuf/struct.proto";

service FooService {
  rpc foo(FooRequest) returns (FooResponse) {
    option (google.api.http) = {
      post: "/foo-message"
      body: "msg"
      additional_bindings: {
        post: "/foo-struct"
        body: "str"
      };
    };
  }
}

message FooRequest {
  oneof payload {
    string msg = 1;
    google.protobuf.Struct str = 2;
  }
}

message FooResponse {}
```

It successfully generates the `pb.gw.go` file, but `go build` fails as:
```
./foo.pb.gw.go:40: protoReq.Msg undefined (type FooRequest has no field or method Msg)
./foo.pb.gw.go:61: protoReq.Str undefined (type FooRequest has no field or method Str)
```

The related line looks like:
```go
if err := marshaler.NewDecoder(req.Body).Decode(&protoReq.Msg); err != nil {
```

The generated go type has the name of field as `Payload` (the name of oneof) rather than individual oneof names, and that field accepts `FooRequest_Msg` or `FooRequest_Str` type. Maybe the codegen can't deal with oneof fields in the body parameter?

### PR DESCRIPTION
**Pull request by yugui**
* `oneof` fields have already been supported in path parameters (#621) and query parameters (#321).
* This PR replaces #416 and fixes #413.

* [ ] oneof fields defined in a message in another package.

### CODE REVIEW

**Comment by Tommy-42** [comment]
hey, thanks for your work !

are there any news about this PR ?

**Comment by johanbrandhorst** [comment]
This seems like it's trying to accomplish the same thing as #570. @yugui are you interested in finishing this?

**Comment by Tommy-42** [comment]
I've opened a PR to update this branch to master state, see : https://github.com/grpc-ecosystem/grpc-gateway/pull/759

**Comment by johanbrandhorst** [comment]
@Tommy-42 if you want to, you can take this branch and rebase on master again, we've fix the CI generation problems.

**Comment by Tommy-42** [comment]
@johanbrandhorst thanks you, I'll try to do something today for it

**Comment by lopezator** [comment]
Is the project alive? Any plans to merge/fix this after more than a year? CC\ @yugui

**Comment by johanbrandhorst** [comment]
> Is the project alive? Any plans to merge/fix this after more than a year? CC\ @yugui

Yes, this project is alive. No, this PR is unlikely to be merged by the original author. Would you be interested in picking up the work in a separate branch?

**Comment by lopezator** [comment]
@johanbrandhorst thanks! Do you know any workaround to be able to make use of one_ofs type fields in the meantime?

**Comment by johanbrandhorst** [comment]
What is the problem with `oneof`? It looks to me like we test `oneof` in body fields already.

**Comment by Starens** [comment]
Hello, are there any plans to resurrect this PR? 
Or is there a more idiomatic way of handling the stated situation nowadays?

**Comment by johanbrandhorst** [comment]
> Hello, are there any plans to resurrect this PR?
> Or is there a more idiomatic way of handling the stated situation nowadays?

Please raise a separate issue if you're having a problem with this. This PR is dead.

**Comment by aesadde** [comment]
Hi 👋  @johanbrandhorst would you accept new PRs for this feature?

It would be cool to be able to use `oneof` fields in request bodies. I'm facing a use case like the following:
```proto
message SimpleMessage {
  ...
  oneof ext {
    int64 en = 6;
    Embedded no = 7;
  }
}

service EchoService {
  rpc EchoBody(SimpleMessage) returns (SimpleMessage) {
    option (google.api.http) = {
      post: "/v1/example/echo_body"
      body: "*"
      additional_bindings {
          put: "/v1/example/echo_body/{id}"
          body: "no"
        }
    };
  }
}
```

I have a working solution and some tests for this (I'm not too familiar with the codebase but used this closed PR as guidance and https://github.com/grpc-ecosystem/grpc-gateway/pull/570) 

Would be more than happy to submit the PR!

**Comment by johanbrandhorst** [comment]
Hi @aesadde. We certainly would be interested in that, please feel free to submit another PR. Thanks!

**Pull request closed without merging**
