### PR TITLE
Added support for Timestamp in URL.

### PR DESCRIPTION
**Pull request by JohanSJA**

### CODE REVIEW

**Comment by tmc** [comment]
@JohanSJA thank you for your contribution. This change looks good -- can you sign your Google CLA?

Are there other values than "null" that need to be special cased? NaN

**Comment by JohanSJA** [comment]
I thought I have signed one before? If not, can you point me to where I should sign for it?

Not sure if we need to handle the other null value though. The code is actually referred from the protobuf project.

**Comment by tmc** [comment]
@JohanSJA looks like googlebot just hadn't reported correctly -- can you resolve the query_test.go conflict? I'd love to see this land.

**Comment by tmc** [comment]
ahem. googlebot?

**Comment by JohanSJA** [comment]
Wake up, googlebot.

**Comment by achew22** [comment]
I want to use this so I'm going to squash and merge. Thanks for your contribution @JohanSJA

**Pull request merged**
