### PR TITLE
feat: add option to disable rendering of service tags

### PR DESCRIPTION
**Pull request by kkolur**
#### References to other Issues or PRs
[Issue #2917](https://github.com/grpc-ecosystem/grpc-gateway/issues/2917#issuecomment-1272779703)

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?
YES

#### Brief description of what is fixed or changed
Add option to disable rendering of service tags for those who wish to not expose the name of their backend grpc services. This allows for greater customizability when generating tags and defining custom tags for the APIs with different grouping strategy.

### CODE REVIEW

**Review by johanbrandhorst — CHANGES_REQUESTED** [review]
Thanks for your PR, this looks great! Just one minor ask from me - could you add a little section about this new feature to our docs page too? We have a `customizing_openapi_output.md` or something like that where we could add a little example of this. Thanks!

**Comment by kkolur** [comment]
> Thanks for your PR, this looks great! Just one minor ask from me - could you add a little section about this new feature to our docs page too? We have a `customizing_openapi_output.md` or something like that where we could add a little example of this. Thanks!

@johanbrandhorst done!

**Review by johanbrandhorst — APPROVED** [review]
LGTM!

**Comment by johanbrandhorst** [comment]
I'll be making a new release pending #2904

**Comment by same-id** [comment]
That's crazy, I was missing this feature and cloned the repository to add it myself, after cloning it was already there.

Using `@master` instead of `@latest` :-)

I'm still missing the feature to add description to custom tags that are generated from adding `tags: repeated string` to methods.

Would love to see that feature / add it myself

**Comment by kkolur** [comment]
> That's crazy, I was missing this feature and cloned the repository to add it myself, after cloning it was already there.
> 
> 
> 
> Using `@master` instead of `@latest` :-)
> 
> 
> 
> I'm still missing the feature to add description to custom tags that are generated from adding `tags: repeated string` to methods.
> 
> 
> 
> Would love to see that feature / add it myself 

@same-id If you see the reference I linked to the PR, I requested soemthing along those lines as well. I use ReDoc instead of Swagger UI to host the OpenAPI spec and tags are a great way to provide an introduction or brief overview of a set of APIs which is pretty important imo.

I would love to be able to add descriptions to tags as well as support tag extensions as well. This would make this tool a lot more versatile and user friendly with ReDoc users as well and I could look into the work 😃 

@johanbrandhorst thoughts?

**Comment by johanbrandhorst** [comment]
Looks like @same-id already took care of it: #2939

**Pull request merged**
