### PR TITLE
Make grpc-gateway support enum fields in path parameter

### PR DESCRIPTION
**Pull request by linuxerwang**
Repeated enum fields are also supported.

### CODE REVIEW

**Comment by tmc** [comment]
Thanks for your contribution, could you please show this behavior in a test case? Also please be mindful of unrelated changes in diffs (there's some whitespace noise). Also please sign the CLA.

**Comment by linuxerwang** [comment]
Done the code changes. I think I've already signed the CLA:

It looks like you've already signed this CLA. If you'd like to edit your contact information, you may do so below.

Not sure what to do next.

Thanks!

**Comment by achew22** [comment]
@tmc This looks like it's good to go for me. Do you object to it?

**Comment by tmc** [comment]
@achew22 LGTM

**Pull request merged**
