### PR TITLE
added additional info for custom http headers

### PR DESCRIPTION
**Pull request by cemenson**
Hi all,

First pull request (ever). Love grpc-gateway, keep up the great work!

I've made a couple of tiny changes to the "Customizing Your Gateway" docs page:

1. Added a `HeaderMatcherFunc` example, showing a couple of ways of returning the custom header key.
2. Added a small example of sending a response header from the server using `gRPC.SendHeader()` as well as a small pointer to the gRPC metadata docs for more info.

That's it! It would have help me a little if they were there when I was setting this up for the first time, so I'm hoping this will help others. 

Thanks!

### CODE REVIEW

**Comment by achew22** [comment]
@cemenson welcome to the party! :tada: :balloon: :tada: 

This is a great first PR on a project and great first contribution to the open source world. Thank you so much for taking the time to fix something that didn't look right. This is how open source gets better.

I look forward to your next PR, and if there is anything I can do to have it be one that enhances this project, just let me know.

Thanks again!

**Comment by cemenson** [comment]
Thanks @achew22! Glad to help!

**Comment by cemenson** [comment]
Sorry, such a noob. Am I supposed to close this PR?

**Comment by achew22** [comment]
No, but I appreciate your trying to help. On my side there is a "merge" button which I needed to hit. However, I wanted to make sure the tests passed before submitting. Sorry I forgot about this tab and just got back to it. It should be merged now in the `master` branch of the repo.

**Pull request merged**
