### PR TITLE
support xml

### PR DESCRIPTION
**Pull request by qianlnk**
marshals/unmarshals into/from XML with the standard "encoding/xml" package.

replace xml's root name to "xml".

### CODE REVIEW

**Comment by tmc** [comment]
@qianlnk bizarrely awesome! can you fix CI and sign the CLA?

**Comment by qianlnk** [comment]
@tmc I'm really want to fix CI, But it work on my PC, I don't know why it FAIL here

my local:
```shell
➜  runtime git:(master) ✗ go test -v -run TestAnnotateContext_WorksWithEmpty
=== RUN   TestAnnotateContext_WorksWithEmpty
--- PASS: TestAnnotateContext_WorksWithEmpty (0.00s)
	context_test.go:26: {GET http://www.example.com HTTP/1.1 1 1 map[Some-Irrelevant-Header:[some value]] <nil> 0 [] false www.example.com map[] map[] <nil> map[]   <nil> <nil> <nil> <nil>}
	context_test.go:28: context.Background.WithValue(metadata.mdKey{}, metadata.MD{"x-forwarded-host":[]string{"www.example.com"}})
	context_test.go:34: map[x-forwarded-host:[www.example.com]] true
PASS
```

and CI

```shell
=== RUN   TestAnnotateContext_WorksWithEmpty
--- FAIL: TestAnnotateContext_WorksWithEmpty (0.00s)
	context_test.go:33: Expected 1 metadata items in context; got map[]
=== RUN   TestAnnotateContext_ForwardsGrpcMetadata
--- FAIL: TestAnnotateContext_ForwardsGrpcMetadata (0.00s)
	context_test.go:55: metadata items in context = 0 want 5: map[]
	context_test.go:58: md["grpcgateway-foobar"] = []; want ["Value1"]
	context_test.go:61: md["grpcgateway-foo-baz"] = [] want ["Value2" "Value3"]
	context_test.go:64: md["grpcgateway-authorization"] = [] want ["Token 1234567890"]
	context_test.go:67: md["authorization"] = [] want ["Token 1234567890"]
=== RUN   TestAnnotateContext_XForwardedFor
--- FAIL: TestAnnotateContext_XForwardedFor (0.00s)
	context_test.go:87: Expected 2 metadata items in context; got map[]
	context_test.go:90: md["host"] = []; want [bar.foo.example.com]
	context_test.go:94: md["x-forwarded-for"] = [] want [192.0.2.100, 192.0.2.200]
```

Why?

**Comment by qianlnk** [comment]
[https://github.com/gogo/protobuf](https://github.com/gogo/protobuf) support custom struct tag for xml

or 

[https://github.com/favadi/protoc-go-inject-tag](https://github.com/favadi/protoc-go-inject-tag)

**Comment by achew22** [comment]
@qianlnk I'm with @tmc on this. Super nifty! Could you also add some tests to verify behavior? This isn't a feature that I have need for and I'm worried we will accidentally break it in the future without noticing.

Thanks!

**Comment by writeameer** [comment]
Hello Everyone,

Just started playing with this wonderful project. I have a use case where xml would be useful. Any reason this wasn't merged ?

Ameer.

**Comment by achew22** [comment]
@writeameer, thanks for the kind words! I like this project a lot as well. The xml handling is a really interesting potential feature, but given the limited use case I'm reluctant to merge it unless there are very good tests for it. Without tests it's likely that it will be broken without anyone noticing. If this is something you need in your project, since it is a marshaller and therefore very pluggable, feel free to use it even though it isn't merged.

**Comment by johanbrandhorst** [comment]
I will leave this open, but this will require major work before it can be merged.

**Comment by johanbrandhorst** [comment]
Please rebase on master for new CI functionality.

**Comment by johanbrandhorst** [comment]
Going to close this as stale

**Pull request closed without merging**
