### PR TITLE
Return codes.InvalidArgument to rather return HTTP 400 instead of HTTP 500

### PR DESCRIPTION
**Pull request by vaporz**
1, Same change in "template.go" with #397 .  
2, Add a test case.  
3, Update examples

### CODE REVIEW

**Comment by vaporz** [comment]
Ah...."Waiting for status to be reported", why....

**Comment by vaporz** [comment]
I signed it!

**Comment by vaporz** [comment]
zzzZZZ

**Comment by vaporz** [comment]
ping @TamalSaha ,
Thank you.

**Comment by pieterlouw** [comment]
I will close #397 as this PR have test case and examples

**Comment by vaporz** [comment]
Hi, any comments on this PR?
Thanks!

**Comment by TamalSaha** [comment]
LGTM.

**Comment by jinleileiking** [comment]
#405

**Comment by jinleileiking** [comment]
The return message is: 
```
{"error":"type mismatch, parameter: num, error: strconv.ParseInt: parsing \"aaa\": invalid syntax","code":3}
```

We should completely customize this return.( Use template?)

We should not change the core code. We need a config file  ??? to set this line:
```
+		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", {{$param | printf "%q"}}, err)
```

**Pull request merged**
