### PR TITLE
Rename packages to follow the repository transfer

### PR DESCRIPTION
**Pull request by yugui**
github.com/gengo/grpc-gateway was transferred to github.com/grpc-ecosystem/grpc-gateway.

### CODE REVIEW

**Comment by yugui** [comment]
Question to reviewers.
What is the recommended protobuf package name for grpc-gateway?

It used to be `gengo.grpc.gateway` and I tentatively replaced it with `grpc.gateway`.  Is there any other recommended option?

* https://github.com/grpc-ecosystem/grpc-gateway/pull/192/commits/2a6dbec2493b8e6ab504481cf0fdb0bd43afa9b2#diff-c810b38ee43b494b6b43d05835936c8cR3
* https://github.com/grpc-ecosystem/grpc-gateway/pull/192/commits/2a6dbec2493b8e6ab504481cf0fdb0bd43afa9b2#diff-15333c7f3c03bc3e7993d7e1afe5dea4R2

**Comment by zinuga** [comment]
@hsaliak any recommendation here?

**Comment by hsaliak** [comment]
/cc @iamqizhao our Go implementation lead for his inputs.
My 2c is that grpc.gateway is suitable -  this is the canonical and popular gateway implementation, and grpc.gateway is a clear name to describe the package's intent.

**Comment by tmc** [comment]
+1 on `grpc.gateway` -- can this move forward as this is in a bit of an awkward state at the moment.

**Comment by iamqizhao** [comment]
grpc.gateway sounds good.

**Comment by hsaliak** [comment]
thanks! @yugui please feel free to merge the proposed changes.

**Comment by yugui** [comment]
Thank you for your reviews. Merged.

**Pull request merged**
