### PR TITLE
add OpenTracing support to docs

### LINKED ISSUE #348: docs: show example of tracing over http->grpc boundary
We should show how to propagate an incoming traced http request over the grpc boundary.

Further, perhaps this just be supported out of the box.

### PR DESCRIPTION
**Pull request by theRealWardo**
closes #348

### CODE REVIEW

**Comment by achew22** [comment]
Can you please rebase this off of maytter please?

**Comment by theRealWardo** [comment]
@achew22 I assume you meant `master` which I've rebased on.

**Comment by achew22** [comment]
Yep -- sorry about that. Typing is hard

**Comment by achew22** [comment]
As always @theRealWardo, thanks so much! It's a pleasure getting to do this with you

**Pull request merged**
