### PR TITLE
Explicitly load rules_proto rules

### PR DESCRIPTION
**Pull request by achew22**
Fixes: #1101

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
> ERROR: error loading package 'internal': Label '//third_party/bazel_rules/rules_proto/proto:defs.bzl' is invalid because 'third_party/bazel_rules/rules_proto/proto' is not a package; perhaps you meant to put the colon here: '//:third_party/bazel_rules/rules_proto/proto/defs.bzl'?

**Comment by achew22** [comment]
Sorry @johanbrandhorst I started this at work but then had to do work things. Will handle "soon"

**Comment by drigz** [comment]
IIUC it's not possible to fix this as a rules_go update is not available. I pinged the reporter: https://github.com/googlecloudrobotics/core/issues/24#issuecomment-566999976

**Comment by achew22** [comment]
@drigz, I don't think we depend on the codepath in `rules_go` that's also needs to be upgraded.

@johanbrandhorst PTAL (sorry it's all greek to you)

**Pull request merged**
