### PR TITLE
Bugfix/issue 2681

### LINKED ISSUE #2681: protoc-gen-openapiv2: Description is sometimes not set in parameter spec.
## 🐛 Bug Report
I generate swagger for a post method with request body
but the method message has no "parameters.schema.description " field when I set the option " json_schema.description" for the message

## To Reproduce

(Write your steps here:)

1. this is my protobuf
2. 
image

```protobuf
service Test{
    rpc AMethod (AMessage) returns (SomeResponse) {
        option (google.api.http) = {
            post: "/v1/projects/someotherpath"
            body: "*"
        };
    }
    rpc BMethod (AMessage) returns (SomeResponse) {
        option (google.api.http) = {
            post: "/v1/projects/someotherpath/{project_id}"
            body: "*"
        };
    }
}
message AMessage {
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
        json_schema:{
            title:"TITITI测试时"
            description: "PPPPPP"
        };
    };
    string project_id = 1;
    string other_field = 2;
}
```
3. generated swagger paths  is following:
image

## Expected behavior
 "/v1/projects/someotherpath"  and  "/v1/projects/someotherpath/{projectId}" both have a parameter named  [body]  with [schema.description] field 

## Actual Behavior
"/v1/projects/someotherpath/{projectId}" path has a parameter named  [body] with a [schema.description] field
but  "/v1/projects/someotherpath"  parameter named  [body]  has  no   [schema.description] field 

## Your Environment
version is 2.10.0

### PR DESCRIPTION
**Pull request by olegvelikanov**
#### References to other Issues or PRs
Fixes #2681 

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?
Yes

#### Brief description of what is fixed or changed
In case of empty binding PathParams we still might want to set description field in parameter spec. 
Currently only schema reference is set. 

#### Other comments
This is my first pull request in an open source project, so I may not fully understand how to properly comment commits or name pull requests, but I hope I did everything right. I just decided to try to contribute something in an open source project and picked a random issue in a project that I use a lot.

### CODE REVIEW

**Review by johanbrandhorst — CHANGES_REQUESTED** [review]
Hi, thank you for your interest in the project! I think we'll need to regenerate the files to see if this causes any changes to our corpus of test files. You can see CONTRIBUTING.md for a guide on how to regenerate our protobuf files.

**Comment by olegvelikanov** [comment]
Hi!
I regenerated files using docker command. I see that body description was added in some swagger files but I'm not sure that all of those changes are correct.

**Review by johanbrandhorst — CHANGES_REQUESTED** [review]
Hi, the generated file changes look correct to me 😄. One more thing - there's an error with the bazel job, and that's because you still haven't run the bazel command that's required. Try running the commands in CONTRIBUTING.md again, or if that doesn't work, you can manually edit the file as the `bazel` job error describes.

**Review by johanbrandhorst — APPROVED** [review]
LGTM

**Comment by olegvelikanov** [comment]
Hi @johanbrandhorst!

Thank you for your approve. Can this PR be merged now?

**Pull request merged**
