### PR TITLE
protoc-gen-grpc-gateway: flip request_context default to true

### PR DESCRIPTION
**Pull request by srenatus**
Follow up to #473.

### CODE REVIEW

**Comment by srenatus** [comment]
(Oh dear that CLA check really takes a while. 😃)

**Comment by srenatus** [comment]
No love for this? 💔 
😉

**Comment by achew22** [comment]
Not to imply that it isn't a desirable change but it is definitely a breaking change since anyone using go 1.7 (which is part of our testing matrix) is going to have a bad time with this.

**Comment by srenatus** [comment]
@achew22 Thanks for the input. Is it still desirable to have 1.7 supported and as part of the testing matrix? 😃

**Comment by achew22** [comment]
I just tagged a new release and as such it is a great time to be turning on new features like this. If people have issues they can use the tag v1.3

**Pull request merged**
