### PR TITLE
Handle wrapper proto types as primitives

### PR DESCRIPTION
**Pull request by nirshirion**
#367

### CODE REVIEW

**Comment by tmc** [comment]
Thanks for your contribution. Have you signed the CLA?

Can you include a test demonstrating this behavior change?

**Comment by achew22** [comment]
@nirshirion I would like to merge this if it is possible. Would you be willing to sign the CLA?

**Comment by achew22** [comment]
@nirshirion, could you sign the CLA and add some tests so that we can merge this?

**Comment by achew22** [comment]
The CLA bot web UI is reporting that you have signed the CLA. Looks like we just need a test and we can submit this. I would love to have it in the project.

**Comment by mattolson** [comment]
👍 We are running into this as well, and feel that this should be handled transparently by grpc-gateway. Are there any blockers to merging this?

**Comment by achew22** [comment]
@mattolson, I don't think there is anything blocking us merging this except test coverage

**Comment by achew22** [comment]
@nirshirion, any chance we could have you come back and add tests to this PR? I would love to merge it!

@mattolson, if you want to take a whack at extending this PR by pulling it into your workspace and writing the tests for it, I would also be happy to merge that.

**Comment by johanbrandhorst** [comment]
Support for this was merged with #695 and #496 :tada:

**Pull request closed without merging**
