### PR TITLE
Rename protoc-gen-swagger to protoc-gen-openapi

### PR DESCRIPTION
**Pull request by johanbrandhorst**

### CODE REVIEW

**Comment by achew22** [comment]
Do you want to specify v2?

**Comment by achew22** [comment]
To be clear openapi v2?

**Comment by johanbrandhorst** [comment]
That would force us to rewrite it with a new name if we wanted to support v3 right?

**Comment by johanbrandhorst** [comment]
> To be clear openapi v2?

Thinking more about this, I think you're right. I'll rename the binary

**Pull request merged**
