### PR TITLE
Skip unreferenced messages in definitions.

### PR DESCRIPTION
**Pull request by Lantame**
If all message fields are embedded in path + query args,
the message itself is not referenced, so swagger generates
warnings.

Here we track request messages referenced in methods, and do not include
unreferenced ones.

### CODE REVIEW

**Comment by tmc** [comment]
@Lantame thanks for your contribution. This looks like a good change. What do you think about adding a small test that verifies this behavior? Also, have you signed the CLA?

**Comment by Lantame** [comment]
Yes, I signed the CLA 8 hours ago. But somehow this check does not pass :-(

**Comment by Lantame** [comment]
Added a test. @tmc take a look pls.

**Comment by tmc** [comment]
@Lantame thanks! can you comment again to try to kick the cla bot into action?

**Comment by Lantame** [comment]
Hello CLA bot!

**Pull request merged**
