### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by NathanBaulch**
Just thought I'd contribute some typo fixes that I stumbled on. Nothing controversial (hopefully).

Use the following command to get a quick summary of the specific corrections made:
```shell
git diff HEAD^! --word-diff-regex='\w+' -U0 \
  | grep -E '\[\-.*\-\]\{\+.*\+\}' \
  | sed -r 's/.*\[\-(.*)\-\]\{\+(.*)\+\}.*/\1 \2/' \
  | sort | uniq -c | sort -n
```

FWIW, the top typos are:
* reponse (7)
* insenstive (5)
* otional (4)
* infront (4)
* vversion (3)
* expecte (2)
* implmented (1)
* intentionaly (1)
* mesage (1)
* direcly (1)
* erorr (1)
* expcted (1)
* previouly (1)
* provices (1)
* spcifying (1)

### CODE REVIEW

**Review by johanbrandhorst — APPROVED** [review]
Nice, thank you! This is very thorough 🤔.

**Comment by NathanBaulch** [comment]
No worries @johanbrandhorst, any idea why CI seems to be regenerating the typos?

**Comment by johanbrandhorst** [comment]
> No worries @johanbrandhorst, any idea why CI seems to be regenerating the typos?

Looks like the files that have the typos now are part of the swagger-codegen generated files, so we can't do anything about them here (except maybe update our dependency). I would recommend you revert the changes to the `configuration.go` files.

**Comment by NathanBaulch** [comment]
Ah, I see - https://github.com/swagger-api/swagger-codegen/blob/61cfeac3b9d855b4eb8bffa0d118bece117bcb7d/modules/swagger-codegen/src/main/resources/go/client.mustache#L104
Normally I'd upstream the fixes but I'm more of an openapi-generator kinda guy 😛

**Pull request merged**
