### PR TITLE
Remove Http Close Notifier

### PR DESCRIPTION
**Pull request by srikrsna**
#736

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Thanks for your PR! You'll need to regenerate the examples with `make examples`. Make sure you've installed the correct version of `protoc` and `protoc-gen-go`.

**Comment by johanbrandhorst** [comment]
At least one of the generation jobs failed, so it looks like you're not using the correct versions of `protoc` and `protoc-gen-go` to generate the examples. You'll need `protoc` version [`3.1.0`](https://github.com/grpc-ecosystem/grpc-gateway/blob/7916b03771e9edb045fcfc7db5f516f8b6a29c39/.travis.yml#L74) and `protoc-gen-go` version [`1.1.0`](https://github.com/grpc-ecosystem/grpc-gateway/blob/7916b03771e9edb045fcfc7db5f516f8b6a29c39/Gopkg.toml#L41).

**Comment by johanbrandhorst** [comment]
@maros7 if you want to commandeer this please open a new PR rebased on master and I will close this one. @srikrsna if you want to finish this off, please rebase on master and follow the new regeneration instructions.

**Comment by johanbrandhorst** [comment]
See https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md#i-want-to-regenerate-the-files-after-making-changes

**Comment by srikrsna** [comment]
Apologies @johanbrandhorst I've tried to do this several times but some reason it constantly fails. I am closing this request.

**Pull request closed without merging**
