### PR TITLE
Merge v2 into master

### LINKED ISSUE #1223: v2 release planning
I figured we should have an issue to track the outstanding work for tagging a first stable v2 version of the gateway and switching the default branches. I've looked through the issue tracker and I think these are some of the issues we want to tackle:

- [x] Issues mentioned in https://github.com/grpc-ecosystem/grpc-gateway/pull/546, including:
   - [x] Emitting defaults (https://github.com/grpc-ecosystem/grpc-gateway/issues/233)
   - [x] Using jsonpb marshaller by default
   - [x] Changing the output of errors to match the JSON representation of a gRPC `status` (https://github.com/grpc-ecosystem/grpc-gateway/issues/1098).
   - [x] Adopt correct behaviour for custom verbs (see https://github.com/grpc-ecosystem/grpc-gateway/issues/224#issuecomment-426091809).
   - [x] Change default JSON marshalling to use camelCase (https://github.com/grpc-ecosystem/grpc-gateway/pull/540) (and update swagger: https://github.com/grpc-ecosystem/grpc-gateway/issues/375)
- [x] Switch to using the new Go protobuf stack (depends on https://github.com/grpc/grpc-go/pull/3453) (https://github.com/grpc-ecosystem/grpc-gateway/pull/1165 is the first part of this). #1147 #1719
- [x] Use `rules_go` version which support APIv2 well known types (https://github.com/bazelbuild/rules_go/issues/2514)
- [x] Minimize public API per https://github.com/grpc-ecosystem/grpc-gateway/pull/1146
- [x] Rename swagger to openapi (https://github.com/grpc-ecosystem/grpc-gateway/issues/675)
- [x] Consolidate error handler configuration.
- [x] Make HTTPBodyMarshaler behaviour the default
- [x] Remove `runtime.DisallowUnknownFields`

I will update this issue as we find more things we want to have in a v2 release. I've also updated the v2 milestone: https://github.com/grpc-ecosystem/grpc-gateway/milestone/3.

### PR DESCRIPTION
**Pull request by johanbrandhorst**
Draft change of merging v2 into master. Probably have to freeze `v2` and `master` from now until I can merge this. I'm going to come back to this and update things that are missing/incorrect before we can make the release.

Fixes #1223

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
OH COME ON CLA BOT

**Comment by ivucica** [comment]
Latest state I just checked is -- the automation believes this PR needs the following:

- author consent from:  @srenatus, @bvwells, @achew22, @plaflamme 
  - can you please each reply with `@googlebot I consent` ?
    - I'm ~ok skipping this if it takes too long
- CLA from: @odsod, @kentdotn
  - can you please each sign the CLA at https://cla.developers.google.com/ ?
  - if you did this already, apologies, it's the automation that believes you didn't and I can't easily check why

I haven't checked in great detail why this passed before, but the above is the easiest way to unblock this. The second easiest way (for some definition of easiest) is to un-merge the affected contributions.

I do have another way to tackle this, but it wouldn't make me as, uh, comfortable. Let's consider it last resort if all CLAs are indeed on file. I'm ok with flipping the relevant bit if we _just_ resolve the CLA issue.

I don't know why the bot said 'CLAs are signed' here, and the debug tool says they aren't.

**Comment by achew22** [comment]
@googlebot I consent

**Comment by kentdotn** [comment]
@googlebot I consent.

**Comment by kentdotn** [comment]
Hmm, https://cla.developers.google.com/ said that I've already signed in on Jun 7th.

**Comment by bvwells** [comment]
@googlebot I consent

**Comment by srenatus** [comment]
@googlebot I consent

**Comment by ivucica** [comment]
@kentdotn I'll take a closer look, but if you did and the tool still claims the opposite, I'll flip a bit and raise the issue with appropriate people. Thanks for the contributions!

**Comment by johanbrandhorst** [comment]
I've gone through all the changes and they all look right. I'll prepare the `v1` branch from current master, then as soon as CLA bot is ~terminated~happy we can merge this.

**Comment by plaflamme** [comment]
@googlebot I consent.

**Comment by ivucica** [comment]
Everything else is now green except CLA for @kentdotn and @odsod. Manual check by entering the username also gives me a red warning.

Kent, did you use the exact same username to submit the CLA?

FTR the emails that PR tool sees are `kentdotn@users.noreply.github.com` and `os....sod...@gmail.com` [mangled] and the usernames as above. I will open an internal bug for @kentdotn straight away.

**Comment by odsod** [comment]
I've signed the CLA just now - should be all good on my end!

**Comment by ivucica** [comment]
I believe the issue is that PR #1446 had a `gmail.com` address for @kentdotn, while the CLA bot sees the default github.com noreply address.

For @odsod in #PR 1504, there was an `einride.tech` address.

The new patches in this PR have different addresses for some reason? I'll file this as an edge case that could be supported.

**Comment by ivucica** [comment]
@googlebot please be nice and recheck (though I fully expect you'll fail).

I'd like to let authors of the bot take a look at this by Tuesday afternoon GMT, and **after that I'll flip the flag manually**. The CLAs were in place when the PRs were submitted (the bot said so!), the authors said they've signed CLAs here in this thread, hence it's reasonable to proceed with "this is fine".

**Comment by ivucica** [comment]
@kentdotn Looks like your registration with the gmail.com address has Github username `https://github.com/kentdotn` (with the prefix). I'm told that preventing this will be implemented in future.

Can you fix the username? I'm told you may need to revoke and re-sign your CLA. If you're asked about the username, make sure you enter just `kentdotn`.

**Comment by kentdotn** [comment]
@googlebot I consent.

**Comment by kentdotn** [comment]
@googlebot I fixed it.

**Comment by kentdotn** [comment]
@googlebot I consent.

**Comment by kentdotn** [comment]
@ivucica I've changed `username` field in `Edit Contact Information` page but It seems it doesn't fix the situation.
Do you know how to revoke the contract? I couldn't find such buttons or links in https://cla.developers.google.com/clas or `Edit Contact Information`.

**Comment by ivucica** [comment]
I'm flipping the bit.

**Pull request merged**
