### PR TITLE
Fixes additional paths generated when many methods have the same resource path

### LINKED ISSUE #2489: protoc-gen-openapiv2 generates additional paths when API includes several services with resource name based paths
## 🐛 Bug Report

When specifying a gRPC API with multiple services with resource name based paths, and these services have multiple methods for these paths, extra paths are generated in the OpenAPI file; each service in the proto file gets one extra set of paths per method per number of services below with the same path.

## To Reproduce

1. Make a proto definition of your API, e.g. `test/foo_api.proto`:
```
syntax = "proto3";

package test;

option go_package = "example.com/test";

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

service FooService {
  rpc GetFoo(GetFooRequest) returns (Foo) {
    option (google.api.http) = {
      get: "/v1/{name=foos/*}",
    };
  }
  rpc DeleteFoo(DeleteFooRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/v1/{name=foos/*}"
    };
  }
}

message GetFooRequest {
  string name = 1;
}

message DeleteFooRequest {
  string name = 1;
}

message Foo { }

service BarService {
  rpc GetBar(GetBarRequest) returns (Bar) {
    option (google.api.http) = {
      get: "/v1/{name=bars/*}"
    };
  }
  rpc DeleteBar(DeleteBarRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/v1/{name=bars/*}"
    };
  }
}

message GetBarRequest {
  string name = 1;
}

message DeleteBarRequest {
  string name = 1;
}

message Bar { }
```

2. Make sure you have `google/api/annotations.proto` and `google/api/http.proto` available in the include path.

3. Generate the OpenAPIv2 file: `protoc -I . --go_out=. --go_opt=module=example.com/test --go-grpc_out=. --go-grpc_opt=module=example.com/test --openapiv2_out . test/foo_api.proto`

(I originally encountered this issue using `allowMerge=true`, but it occurs with a single file containing multiple services as well.)

## Expected behavior

The file should only contain paths `/v1/{name}` and `/v1/{name_1}`. Each path should only apply to one service.

## Actual Behavior

The resulting file contains three paths with get and delete operations, mixed between the two services (`responses` removed for readability):
```
  "paths": {
    "/v1/{name_1}": {
      "get": {
        "operationId": "BarService_GetBar",
        "parameters": [
          {
            "name": "name_1",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "bars/[^/]+"
          }
        ],
        "tags": [
          "BarService"
        ]
      },
      "delete": {
        "operationId": "FooService_DeleteFoo",
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "foos/[^/]+"
          }
        ],
        "tags": [
          "FooService"
        ]
      }
    },
    "/v1/{name_2}": {
      "get": {
        "operationId": "FooService_GetFoo",
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "foos/[^/]+"
          }
        ],
        "tags": [
          "FooService"
        ]
      },
      "delete": {
        "operationId": "BarService_DeleteBar",
        "parameters": [
          {
            "name": "name_2",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "bars/[^/]+"
          }
        ],
        "tags": [
          "BarService"
        ]
      }
    },
    "/v1/{name}": {
      "get": {
        "operationId": "FooService_GetFoo",
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "foos/[^/]+"
          }
        ],
        "tags": [
          "FooService"
        ]
      },
      "delete": {
        "operationId": "FooService_DeleteFoo",
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "foos/[^/]+"
          }
        ],
        "tags": [
          "FooService"
        ]
      }
    }
  }
```

## Your Environment

macOS: 12.0.1
protoc: `libprotoc 3.17.3`
go: `go version go1.17.2 darwin/amd64`
grpc-gateway: 2.7.2

### PR DESCRIPTION
**Pull request by aethanol**
#### References to other Issues or PRs

Fixes #2489

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?
Yes

#### Brief description of what is fixed or changed
This adds tests and fixes the small regression introduced in #2461.

#### Other comments
More tests should probably be written, and specifically a test with multiple services and multiple same paths.

### CODE REVIEW

**Comment by aethanol** [comment]
Raised this PR preemptively, it regresses `TestTemplateWithDuplicateHttp1Operations`.

**Comment by aethanol** [comment]
This should be correct now! though I think I noticed another bug where when methods with the same generated path are not in order, it will generate a valid, but not ideal schema.
Eg.

```
syntax = "proto3";

package test;

option go_package = "example.com/test";

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

service Service1 {
  rpc DeleteBar(DeleteBarRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/v1/{name=bars/*}"
    };
  }
  rpc GetFoo(GetFooRequest) returns (Foo) {
    option (google.api.http) = {
      get: "/v1/{name=foos/*}",
    };
  }
  rpc DeleteFoo(DeleteFooRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/v1/{name=foos/*}"
    };
  }
  rpc GetBar(GetBarRequest) returns (Bar) {
    option (google.api.http) = {
      get: "/v1/{name=bars/*}"
    };
  }
}

message GetFooRequest {
  string name = 1;
}

message DeleteFooRequest {
  string name = 1;
}

message Foo { }


message GetBarRequest {
  string name = 1;
}

message DeleteBarRequest {
  string name = 1;
}

message Bar { }
```

will generate a schema with path `/v1/{name}` having `DeleteBar` and `GetFoo` and `/v1/{name_1}` having `DeleteFoo` `GetBar`. This is technically valid, but will probably make generated clients weird.

The potential solution would be to check that the param pattern is the same when adding to existing objects.

**Review by johanbrandhorst — APPROVED** [review]
Thanks for the quick fix, and thanks @oyvindwe for confirming the fix!

**Comment by johanbrandhorst** [comment]
Closing and reopening PR to see if I can trigger CI again 🙄

**Comment by johanbrandhorst** [comment]
Thanks for your contribution!

**Comment by aethanol** [comment]
> Thanks for your contribution!

Glad to help! also what is the release schedule for grpc-gateway like? Or if you had a rough eta? I am contributing this change back to https://github.com/grafeas/grafeas

**Comment by johanbrandhorst** [comment]
I can cut a new release :). There's no particular schedule.

**Comment by johanbrandhorst** [comment]
https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v2.7.3

**Pull request merged**
