### PR TITLE
[]byte in query now uses base64.StdEncoding

### PR DESCRIPTION
**Pull request by lucasvo**
This fixes the issue with different base64 string encoding in query params and json representations in the request body discussed in #423

@loderunner Care to review?

### CODE REVIEW

**Comment by lucasvo** [comment]
Signed the CLA.

**Comment by loderunner** [comment]
Looks fine to me!

The burden will be on the client to correctly escape the query parameters to avoid `/`, `+` and `=`.  I wonder if this is worth documenting somewhere. Perhaps someone from the grpc-gateway project can help us here?

**Comment by achew22** [comment]
Do either of you know if it is possible to use the same base64 en/decoder that is provided by golang/protobuf? How does the deserialization work when they are processing JSONified protos? Could you point me to the code where they do that?

**Comment by loderunner** [comment]
golang/protobuf uses the stdlib json encoding/decoding. The go structs generated from the proto file are annotated for JSON encoding.

Encoding byte slices to base64 is part of the stdlib:

> Array and slice values encode as JSON arrays, except that []byte encodes as a base64-encoded string, and a nil slice encodes as the null JSON value.

[https://github.com/golang/go/blob/master/src/encoding/json/encode.go#L54-L56](Source)

You can find the source for the encoding [here](https://github.com/golang/go/blob/master/src/encoding/json/encode.go#L705-L725) and the decoding [here](https://github.com/golang/go/blob/master/src/encoding/json/decode.go#L967-L973)

I think there is a bit of [custom Marshal/Unmarshal code](https://github.com/golang/protobuf/blob/master/proto/lib.go#L417-L442) for handling enums and their string representations, but nothing for byte slices.

**Comment by lucasvo** [comment]
@loderunner did the heavy lifting, he deserves the credit! Thanks for helping out with this.

**Pull request merged**
