### PR TITLE
Return response headers from grpc server

### PR DESCRIPTION
**Pull request by TamalSaha**
This bug was introduced in #336.

### CODE REVIEW

**Comment by TamalSaha** [comment]
cc: @tmc

**Comment by tmc** [comment]
I'd like to have this exercised under test.

**Comment by tmc** [comment]
I opened #362 previously and this may fit within that definition.

**Comment by achew22** [comment]
2+1 to having a test. @tmc, what do you think about merging to get it fixed and then having @TamalSaha do a followup?

**Comment by tmc** [comment]
@achew22 I think that's acceptable.

**Comment by achew22** [comment]
LGTM once CI approves, I think this better fits into #362

**Comment by TamalSaha** [comment]
Thank you!

**Pull request merged**
