### PR TITLE
Remove Bazel from CircleCI configuration

### PR DESCRIPTION
**Pull request by achew22**
Now that we have Bazel CI configured, this should be a better way of testing it.

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Uh, how do we find out if the bazel build fails? Can we add it to the CI statuses?

**Comment by srenatus** [comment]
Looks like there's badges that could be used: https://buildkite.com/docs/integrations/build-status-badges
> You can find your pipeline's status badge on the Pipeline Settings page.

**Comment by johanbrandhorst** [comment]
We're still working on this behind the scenes :grimacing:. Hopefully should be sorted soon.

**Comment by johanbrandhorst** [comment]
@achew22 whats the latest on getting this working?

**Comment by achew22** [comment]
I still need to do it. Totally forgot about it. Just made a note to do it when I'm at work on monday

**Comment by johanbrandhorst** [comment]
Is this good to go in? I don't know if the buildkite stuff is working yet? @srenatus @achew22.

**Comment by achew22** [comment]
From my perspective it is good to go, but we still don't have the status being included on PRs. @srenatus, do you know what it would take to do that?

**Comment by johanbrandhorst** [comment]
We're clearly still running out of memory sometimes :joy:: https://app.circleci.com/pipelines/github/grpc-ecosystem/grpc-gateway/149/workflows/6f0f633f-d7f6-482a-8e06-c8074f9ebaac/jobs/6589

**Comment by srenatus** [comment]
I can't see those settings in neither grpc-gateway nor bazel's BK settings, but https://github.com/bazelbuild/continuous-integration/issues/385#issuecomment-496551846 looks like something to check? Other than that, reaching out to the bazel BK folks, like you have done, seems the way to go. 

Anyhow, it seems to be running for PRs, like [this one for example](https://buildkite.com/bazel/grpc-ecosystem-grpc-gateway/builds?branch=hb-chen%3Afix-query-params)

**Comment by achew22** [comment]
@ivucica do you have the ability to see the admin page? It would be really nice to see if that setting can be messed with

**Comment by johanbrandhorst** [comment]
We can revisit this later, but I will tentatively say that caching our bazel artifacts (who'da thunk?) has helped ease the instability.

**Pull request closed without merging**
