### PR TITLE
Update v2 generator for new protoc-gen-go-grpc API

### LINKED ISSUE #1655: Update v2 generator for new protoc-gen-go-grpc API
## 🚀 Feature

protoc-gen-go-grpc produces files which are slightly different to the ones which are generated by protoc-gen-go (with plugin grpc). 

[A sample of the needed change can be seen here](https://github.com/veith/grpc-gateway/commit/323bfae3f9d29447450f0e841a113289c610a89d). I posted it to show what i meant. I ask for the flag, because this change can be made without breaking in v1 too.

### PR DESCRIPTION
**Pull request by veith**
#### References to other Issues or PRs
Fixes #1655 

#### Brief description of what is fixed or changed

- For the template it was just [service]Server changed to [service]Service
- For the template_test it was the same

The examples were updated to the current api of protoc-gen-go-grpc which should be stable at the end of this month.
I know that the examples could be done better by me, but i wait for a v1 of  protoc-gen-go-grpc.

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
I think you still need to run the regeneration script, it's done using these two docker commands: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md#i-want-to-regenerate-the-files-after-making-changes.

**Comment by veith** [comment]
> generation script, it's done using these two docker

I will try it...

**Comment by johanbrandhorst** [comment]
I think we're seeing failures now because you must've run `go mod vendor` before running the generation step - this has messed up the bazel dependencies. Could you delete the vendor directory and rerun the generation step?

**Comment by veith** [comment]
Can someone give me a hint, the tests are green and i have run the "regenerate the files after making changes" 

ci/circleci: **generate** fails because of the dependencies i updated

```
-google.golang.org/grpc/cmd/protoc-gen-go-grpc v0.0.0-20200527211525-6c9e30c09db2 h1:KNluVV5ay+orsSPJ6XTpwJQ8qBhrBkOTmtBFGeDlBcY=
-google.golang.org/grpc/cmd/protoc-gen-go-grpc v0.0.0-20200527211525-6c9e30c09db2/go.mod h1:6Kw0yEErY5E/yWrBtf03jp27GLLJujG4z/JK95pnjjw=
 google.golang.org/grpc/cmd/protoc-gen-go-grpc v0.0.0-20200826230536-d31b6710005d h1:uTrqg3Oy/pU93G8krO57J8iJWQnV8uD1EFLMmBDgscs=
 google.golang.org/grpc/cmd/protoc-gen-go-grpc v0.0.0-20200826230536-d31b6710005d/go.mod h1:6Kw0yEErY5E/yWrBtf03jp27GLLJujG4z/JK95pnjjw=
```

And ci/circleci: **bazel** fails on the check if all bazel build files are up to date.

**Comment by veith** [comment]
If required i can update the corresponding documentation too

**Comment by johanbrandhorst** [comment]
We're going to wait with merging this until v1.0.0 of protoc-gen-go-grpc is released.

**Comment by veith** [comment]
> We're going to wait with merging this until v1.0.0 of protoc-gen-go-grpc is released.

Ok, good decision.

**Comment by johanbrandhorst** [comment]
Superceded by #1719

**Pull request closed without merging**
