### PR TITLE
Switch to go modules

### LINKED ISSUE #755: Support go modules
Steps you follow to reproduce the error:

1. Using go1.11 outside of go path
2. Run `go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway`

Returns
```
go: finding github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway latest

# github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway/descriptor

../../go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.5.0/protoc-gen-grpc-gateway/descriptor/services.go:146:49: opts.ResponseBody undefined (type *annotations.HttpRule has no field or method ResponseBody)
-->
```

What did you expect to happen instead:
Successfully added to mod file

It seems like it's able to find the latest version 1.5.0, but then isn't up to date? The error that's output seems to be what was fixed with #731

### PR DESCRIPTION
**Pull request by johanbrandhorst**
Fixes #755 

@achew22 Do I need to do anything more WRT `bazel` here? I've just removed `WORKSPACE` since I assume it's superfluous with the module definitions.

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Obviously still WIP, but I wanted to get the ball rolling on this

**Comment by achew22** [comment]
I think reverting the delete of the WORKSPACE is all you should need to do to get it working in Bazel. Once you merge this I'll do a follow up to upgrade to the latest `rules_go` which has proper support for go modules and clean it up in there a bit.

**Comment by johanbrandhorst** [comment]
I think this should be ready for a review @achew22.

The node tests are still using a vendor folder instead of a GOPATH but that's okay I think.

The generate test now includes running `go mod tidy` afterwards because otherwise it seems to make the resty dependency indirect. I don't understand how that all interacts.

**Comment by johanbrandhorst** [comment]
:tada:

**Pull request merged**
