### PR TITLE
Support delete method in swagger generator

### PR DESCRIPTION
**Pull request by blackdahila**
Solves #559 and generates query parameters for the `delete` method.

### CODE REVIEW

**Comment by tmc** [comment]
Upstream issue fixed, can you rebase to trigger another build?

**Comment by yugui** [comment]
https://travis-ci.org/grpc-ecosystem/grpc-gateway/jobs/370802179 (Go 1.10.x; `GATEWAY_PLUGIN_FLAGS=`) is failing due to the issue solved by #619.
https://travis-ci.org/grpc-ecosystem/grpc-gateway/jobs/370802182 (Go master; `GATEWAY_PLUGIN_FLAGS=request_context=false`) seems to be flaky. And now failing because of incompatibility to #618.

Would you mind rebasing the branch again?

**Comment by blackdahila** [comment]
@yugui done 🙂

**Comment by achew22** [comment]
Can you change one of the proto files to exhibit this new behavior and run `make examples`?

**Comment by blackdahila** [comment]
I've added simple endpoint exhibiting the new behavior to the examples @achew22

**Comment by achew22** [comment]
@blackdahila, I think this is good to go. Thanks so much for your contribution! I look forward to doing it again soon.

**Pull request merged**
