### PR TITLE
Adding docs about controlling http response status codes

### PR DESCRIPTION
**Pull request by zhughes3**
#### References to other Issues or PRs

Adding notes to documentation after repeated discussion in https://github.com/grpc-ecosystem/grpc-gateway/issues/517#issuecomment-633359394

#### Brief description of what is fixed or changed
Added documentation about controlling http response status codes.

### CODE REVIEW

**Comment by zhughes3** [comment]
> @googlebot I signed it!

**Comment by johanbrandhorst** [comment]
> > @googlebot I signed it!

Try this without a quote

**Comment by johanbrandhorst** [comment]
Thanks for your contribution! Could you please cherry pick this against v2?

**Comment by zhughes3** [comment]
@johanbrandhorst Of course! I am trying to cherry pick it into the v2 branch. If you can be patient, my git-fu is still amateur at best.

**Pull request merged**
