### PR TITLE
Swagger example field

### PR DESCRIPTION
**Pull request by srenatus**
Picked up and rebased @birdayz's work on making the `example` field available.

@johanbrandhorst do we have any tests that could be expanded to cover that new field?

(💭 let's see what happens in CI -- locally, the swagger.json got a bit different when running `make examples/proto/examplepb/a_bit_of_everything.swagger.json`...)

### CODE REVIEW

**Comment by srenatus** [comment]
ok, mistake 1: I should have rebuilt the other stuff, too, of course 😅

**Comment by johanbrandhorst** [comment]
Ah, yes, the CLA bot will not like the different approvers. Could you, uh, force push a new history with just your commits?

**Comment by johanbrandhorst** [comment]
To regenerate files, see https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md#i-want-to-regenerate-the-files-after-making-changes

**Comment by srenatus** [comment]
> Ah, yes, the CLA bot will not like the different approvers. Could you, uh, force push a new history with just your commits?

Sure, but that'll only work if it's branched off of #799 or that other PR is merged first (and this rebased) -- which one do you prefer? 😉

**Comment by johanbrandhorst** [comment]
I imagine you could just rebase on and squash the commits so they become yours? I mean, @birdayz can be mentioned as an author in the commit still.

**Comment by srenatus** [comment]
OK, will do.

**Comment by srenatus** [comment]
> Note to project maintainer: This is a terminal state, meaning the cla/google commit status will not change from this state. It's up to you to confirm consent of all the commit author(s), set the cla label to yes (if enabled on your project), and then merge this pull request when appropriate.

This makes me think that this won't fix itself, though... 🤔 Can you change the label, or should I just open another PR?

**Comment by johanbrandhorst** [comment]
I don't have the permission to change it since I'm not a google administrator :grimacing:. I suppose try and create a new one :joy:.

**Pull request closed without merging**
