### PR TITLE
Use org_golang_x_tools as module extension

### PR DESCRIPTION
**Pull request by mering**
#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/CONTRIBUTING.md)?

Yes

#### Brief description of what is fixed or changed

If not using module dependencies, there is a risk of including the same dependency twice as Bzlmod cannot resolve this correctly.

### CODE REVIEW

**Review by johanbrandhorst — APPROVED** [review]
Sweet, thank you

**Comment by mering** [comment]
Oops, I forgot to update the lock file. Should be fixed now.

**Comment by mering** [comment]
How do you update the lockfile correctly? We are not using lockfiles yet.

**Comment by mering** [comment]
I just ran `bazel run //:gazelle` as the CI. Let's see if this fixes it.

**Comment by johanbrandhorst** [comment]
Thanks for your contribution!

**Pull request merged**
