### PR TITLE
Revert "Support HttpRule with field response"

### PR DESCRIPTION
**Pull request by ivucica**
Reverts grpc-ecosystem/grpc-gateway#712

We should roll forward only once these blockers are resolved:
* https://github.com/google/go-genproto/issues/92
* https://github.com/googleapis/api-common-protos/issues/11

### CODE REVIEW

**Comment by ivucica** [comment]
FYI @doroginin @johanbrandhorst @achew22  I will roll this back immediately because we can easily roll forward once it's not friday.

**Comment by johanbrandhorst** [comment]
@ivucica LGTM

**Comment by achew22** [comment]
LGTM. Let's not break weekend hackers

**Comment by ivucica** [comment]
Alright, the change to googleapis/api-common-protos has been merged already!

Looks like someone "just" needs to regenerate code in `go-genproto` and we may not need to merge this. I'll give it ~1.5h and then merge this rollback.

**Comment by johanbrandhorst** [comment]
@ivucica I got in touch with @jadekler, he says this should be fixed?

**Comment by johanbrandhorst** [comment]
Looks like we can close this?

**Comment by ivucica** [comment]
Done

**Pull request closed without merging**
