### PR TITLE
Generate a single swagger definition on demand

### PR DESCRIPTION
**Pull request by achew22**
Combines the efforts of @cy-zheng in #643 with the efforts of @zxy198717 in #591.

Fixes: #643, #591, #99

### CODE REVIEW

**Comment by achew22** [comment]
I manually edited both changes to leave authorship with their respective author, rebased and uploaded. This can now fix a long standing issue. Thanks so much everyone!

**Comment by hexfusion** [comment]
@achew22 any idea when this might be released? Would it make 1.4.x?

**Comment by achew22** [comment]
@hexfusion ask and you shall receive https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v1.4.1

**Comment by hexfusion** [comment]
Perfect thanks a lot!

**Pull request merged**
