### PR TITLE
added Pull Request Template for grpc-gateway

### PR DESCRIPTION
**Pull request by iamrajiv**
added `PULL_REQUEST_TEMPLATE.md` file

### CODE REVIEW

**Comment by iamrajiv** [comment]
sure @johanbrandhorst and I think ISSUE_TEMPLATE.md should also be moved to `.github` WDYT?

**Comment by johanbrandhorst** [comment]
> sure @johanbrandhorst and I think ISSUE_TEMPLATE.md should also be moved to `.github` WDYT?

Great idea, please do!

**Comment by johanbrandhorst** [comment]
Thanks for your contribution! Could you please cherry-pick this against v2?

**Comment by iamrajiv** [comment]
sure @johanbrandhorst

**Pull request merged**
