### PR TITLE
Stop marshalling any.Any types unnecessarily.

### LINKED ISSUE #576: Impossible to use gogo/protobuf registered types in gRPC Status errors
The gRPC-Gateway uses the gRPC `status` package for writing rich gRPC errors to the JSON response of a gRPC call. Unfortunately, the use of `status.Details()` directly assumes all proto message types stored in the status are registered with the `golang/protobuf` proto type registry. Ideally the gRPC Gateway would simply allow the JSON marshaller to marshal the messages, which would leave such type resolution to the marshaller, and not the runtime.

To be specific, this bug refers to the handling of the status in https://github.com/grpc-ecosystem/grpc-gateway/blob/58f78b988bc393694cef62b92c5cde77e4742ff5/runtime/errors.go#L100-L109

### PR DESCRIPTION
**Pull request by johanbrandhorst**
Fixes #576.

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
@achew22 this should be a harmless change, could you take a quick look please?

**Comment by achew22** [comment]
My understanding of the proto registry is unfortunately lacking WRT this topic. My expectation is that the proto on the wire wouldn't contain enough information to serialize it down to json. Does the any proto contain a field => name mapping in the wire format for it or something?

Could you also add a test to ensure this behavior doesn't regress?

**Comment by johanbrandhorst** [comment]
Added a test for marshalling with details.

**Comment by tmc** [comment]
@johanbrandhorst thanks for this, can you rebase and resolve that test conflict?

**Comment by johanbrandhorst** [comment]
@tmc rebase completed!

**Comment by johanbrandhorst** [comment]
@tmc Is that test failure due to my change? It seems unrelated.

**Comment by tmc** [comment]
Sorry I missed your comment. The failure does appear to have been unrelated. Please resolve the conflicts here and let's get this in!

**Comment by johanbrandhorst** [comment]
Rebased :)

**Comment by johanbrandhorst** [comment]
Think I've git a flaky test, could I have a rerun please? @tmc

**Comment by achew22** [comment]
Retriggered

**Comment by johanbrandhorst** [comment]
Looking good on my end, happy to merge?

**Comment by johanbrandhorst** [comment]
Not entirely sure why it's required me to regenerate the protofiles though :thinking:

**Comment by tmc** [comment]
To add ,proto3

**Comment by tmc** [comment]
@achew22 I'll let you complete review and merge

**Comment by achew22** [comment]
LGTM. Looks like there is a merge conflict. It isn't trivial to do from the web interface and I'm at work, but @tmc feel free to merge if you can get it to have no conflicts

**Comment by johanbrandhorst** [comment]
Curses! I'll fix it.

**Comment by johanbrandhorst** [comment]
Alright that should've done it. I had to pull and push over HTTPS as this airport WiFi must be blocking port 22 :thinking:.

**Pull request merged**
