### PR TITLE
protoc-gen-swagger: check typeIndex when typeName is Method

### PR DESCRIPTION
**Pull request by hexfusion**
isProtoPathMatches() doesn't return false if svcIdx != methIdx when typeName == Method. The results in comments belonging to other services polluting swagger spec. We noticed this regression when using protoc 3.5.1+, although I still can't say why it started.

Fixes: https://github.com/grpc-ecosystem/grpc-gateway/issues/746

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Hi @hexfusion, thanks a bunch for the contribution! Any chance you could add some new test casee for this to prevent future regressions? Thanks!

**Comment by johanbrandhorst** [comment]
It seems the generator changes caused a diff in one of the generated files. Is that expected? If so, you'll need to rerun the generator (see CONTRIBUTING.md).

**Comment by hexfusion** [comment]
@johanbrandhorst looking at the source of the proto I believe the change is expected, will update.

**Comment by johanbrandhorst** [comment]
Looks great, thanks!

**Comment by johanbrandhorst** [comment]
A new release you mean? We don't currently have a set release schedule, I can see if we're waiting for anything in particular but I might just release 1.6.4 tomorrow.

**Comment by hexfusion** [comment]
that would be fantastic, and greatly appreciated.

**Comment by johanbrandhorst** [comment]
FYI @hexfusion I will be backing out these changes, it seems they caused #923, please see #924. Please feel free to open another PR reverting the revert where we can add some more tests to ensure we get the best of both worlds.

**Pull request merged**
