### PR TITLE
remove message field from the error message emitted by grpc-gateway

### PR DESCRIPTION
**Pull request by ti**
this is just recovery of the code, the "error" filed is more meaning for than the message

more info: https://github.com/grpc-ecosystem/grpc-gateway/pull/718

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Hi @ti, while I appreciate that the duplication is ugly, I don't think removing the message that we added there for consistency with the googleapis.Status type is the right way to go. We cannot accept this right now for backwards compatbility reasons, but we are also more likely to just remove `error` with version 2.0.

**Comment by ti** [comment]
@ffredsh we should recovery of the code.

**Comment by ti** [comment]
@johanbrandhorst  https://github.com/grpc-ecosystem/grpc-gateway/pull/718

**Comment by johanbrandhorst** [comment]
What do you mean? We added that for the reasons listed in the pull request.

**Pull request closed without merging**
