### PR TITLE
fix SendHeader/SetTrailer when use grpc-gateway standalone server (master)

### PR DESCRIPTION
**Pull request by ghostiam**
Same: https://github.com/grpc-ecosystem/grpc-gateway/pull/1638 but for master branch

### CODE REVIEW

**Comment by ghostiam** [comment]
I don't understand Bazel error:
```
compilepkg: missing strict dependencies:
...
.../grpc-gateway/examples/internal/proto/examplepb/wrappers.pb.gw.go: import of "google.golang.org/grpc/metadata"
...
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
```

examples/internal/proto/examplepb/wrappers.pb.gw.go
```go

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/descriptor"
	"github.com/golang/protobuf/proto"
	"github.com/golang/protobuf/ptypes/empty"
	"github.com/golang/protobuf/ptypes/wrappers"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"     // <-----------
	"google.golang.org/grpc/status"
)
...
var _ = metadata.Join
...
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())

```

examples/internal/proto/examplepb/BUILD.bazel
```
...
go_library(
    name = "go_default_library",
    srcs = ["unannotated_echo_service.pb.gw.go"],
    embed = [":examplepb_go_proto"],
    importpath = "github.com/grpc-ecosystem/grpc-gateway/examples/internal/proto/examplepb",
    deps = [
        "//runtime:go_default_library",
        "//utilities:go_default_library",
        "@com_github_golang_protobuf//descriptor:go_default_library_gen",
        "@com_github_golang_protobuf//proto:go_default_library",
        "@org_golang_google_grpc//:go_default_library",
        "@org_golang_google_grpc//codes:go_default_library",
        "@org_golang_google_grpc//grpclog:go_default_library",
        "@org_golang_google_grpc//metadata:go_default_library",  // <-----------
        "@org_golang_google_grpc//status:go_default_library",
    ],
)
...
```

**Review by johanbrandhorst — CHANGES_REQUESTED** [review]
Same comments as on v2

**Review by johanbrandhorst — APPROVED** [review]

**Comment by johanbrandhorst** [comment]
Thanks for your contribution!

**Comment by ghostiam** [comment]
Thank you too!

**Pull request merged**
