### PR TITLE
Massive breaking changes in preparation for 2.0

### PR DESCRIPTION
**Pull request by achew22**
This PR turned out to be an absolutely gigantic... thing. Since I'm making breaking changes why not break all the things.

Things I broke:

  * Emitting defaults
  * Now uses the jsonpb marshaller by default
  * Upgrade to swagger 2.4

Obviously this can't go in until swagger 2.4 is released, but we have a backlog of significant breaking changes that would improve the quality of the service dramatically. My plan is to cut one last 1.X branch release then merge merge merge and cut a 2.0

# TODO

 * [ ] I need to add an upgrading section to the docs

### CODE REVIEW

**Comment by thurt** [comment]
may want to update # 5 https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md also

**Comment by johanbrandhorst** [comment]
This seems to have suffered some bitrot, which is unfortunate for a large change like this as it'll be a pain to keep rebasing it.

**Comment by johanbrandhorst** [comment]
Other things I'd like for 2.0:

Output errors in the same format as the gRPC-Go `status.Status`, that is, simply use `status.Convert` followed by `marshaller.Marshal`.

**Comment by johanbrandhorst** [comment]
Another one: Adopt the correct behaviour for custom verbs (see https://github.com/grpc-ecosystem/grpc-gateway/issues/224#issuecomment-426091809).

**Comment by johanbrandhorst** [comment]
Please rebase on master for new CI functionality. :grimacing:

**Comment by johanbrandhorst** [comment]
We'd love to have help getting this in for v2, though I'm not sure the original author will have the time.

**Pull request closed without merging**
