### PR TITLE
protoc-gen-swagger/genswagger: add PATCH support

### PR DESCRIPTION
**Pull request by EricLagergren**
Fixes: #211

### CODE REVIEW

**Comment by EricLagergren** [comment]
CLA should be good to go (https://golang.org/CONTRIBUTORS#L340)

**Comment by achew22** [comment]
Thanks so much for sending your PR in. Do you think you could update the example protos to include a "PATCH" and regenerate the generated files? I think "make examples" is all you need to do for that.

Thanks! I look forward to having patch support.

**Comment by EricLagergren** [comment]
Yeah I think I can do it tomorrow, feel free to ping me if I forget :smile:

**Comment by yugui** [comment]
@EricLagergren ping 😉

**Comment by tmc** [comment]
@EricLagergren thank you for your contribution - can you rebase and re-gen examples for this please?

**Comment by tmc** [comment]
@EricLagergren I think you are running a different version of swagger-codegen -- this project currently relies on 2.1.6

**Comment by EricLagergren** [comment]
I think you're right. I used the latest swagger-codegen release, whatever version it is. I thought the massive amount of changes looked weird, but I didn't have time to throughly debug it today. 

I'll revert and re-run it with 2.16 either tonight or tomorrow morning.

**Comment by tmc** [comment]
ping @EricLagergren

**Pull request closed without merging**
