### PR TITLE
[Bug #3829] [protoc-gen-openapiv2] consider openapiv2_tag.name attribute when generating ope…

### LINKED ISSUE #3829: openapiv2_tag.name does not work
## 🐛 Bug Report

openapiv2_tag name attribute is not being considered during generation

## To Reproduce

1. Annotate with openapiv2_tag.name to a name different than the service's name
2. buf generate 

## Expected behavior

name should override the service name in swagger.json artifact.

Please assign this to me if possible - I'm working on a fix

## Actual Behavior

Name doesn't change

## Your Environment

-

### PR DESCRIPTION
**Pull request by omrikiei**
…napi docs

This PR adds code that references the name attribute in the openapiv2 tag attribute.

#### References to other Issues or PRs

Fixes #3829

## Summary by CodeRabbit

- **New Features**
	- Enhanced the API service by adding a new `name` field to improve service identification.

- **Refactor**
	- Improved internal logic to dynamically assign service tag names based on configuration.

### CODE REVIEW

**Review by johanbrandhorst — CHANGES_REQUESTED** [review]
Great spot. I think you'll need to regenerate the files using our version of `buf`. The changes to the other swagger files are because of a newer version of Buf being used. See CONTRIBUTING.md for instructions.

**Comment by omrikiei** [comment]
Hi @johanbrandhorst - Indeed I followed the CONTRIBUTING.md guide.
The docker image is build for amd64 architecture (I use an M1 macbook) and I'm not able to successfully run it..
Building the image as is for my architecture also didn't work - I had to modify the Dockerfile for use the main branch for dev containers and use default JRE - once I was able to build the image I got these artifacts (with extra newlines). these artifacts are the result. Could you try to clone my forked repo and generate with your environment?

**Comment by omrikiei** [comment]
@johanbrandhorst I managed to obtain an arm64 laptop and pushed the artifacts, should work now...

**Comment by johanbrandhorst** [comment]
Looks like there are still some minor test issues, probably some test that now does the right thing?

**Comment by johanbrandhorst** [comment]
Thanks for your contribution! I'll be making a release once https://github.com/grpc-ecosystem/grpc-gateway/pull/3743 is merged.

**Comment by omrikiei** [comment]
Thank you!

**Pull request merged**
