### PR TITLE
fix: output protobufAny definition using correct JSON schema

### LINKED ISSUE #2177: protoc-gen-openapiv2 creates incorrect schema for google.protobuf.Any
## 🐛 Bug Report

I have a message containing a `google.protobuf.Any`, and the resultant `swagger.json` file contains a definition for `protobufAny` with a property `typeUrl` instead of `@type`.

If I use the swagger-ui to make a request following the schema, my grpc-gateway proxy ends up failing because the `Any` field is omitted from the request. If I manually change the request body so that `@type` is defined instead of `typeUrl`, everything works.

## To Reproduce

Create a message like so:

```proto
import "google/protobuf/any.proto";

message MyMessage {
  string id = 1;
  google.protobuf.Any config = 2;
}
```

Running `protoc-gen-openapiv2` using buf (following the instructions from the `README.md`), and I end up with a field in the `definitions` object of the swagger.json:

```json
{
  ...
  "protobufAny": {
      "type": "object",
      "properties": {
        "typeUrl": {
          "type": "string",
          "description": "A URL/resource name that uniquely identifies the type of the serialized\nprotocol buffer message. This string must contain at least\none \"/\" character. The last segment of the URL's path must represent\nthe fully qualified name of the type (as in\n`path/google.protobuf.Duration`). The name should be in a canonical form\n(e.g., leading \".\" is not accepted).\n\nIn practice, teams usually precompile into the binary all types that they\nexpect it to use in the context of Any. However, for URLs which use the\nscheme `http`, `https`, or no scheme, one can optionally set up a type\nserver that maps type URLs to message definitions as follows:\n\n* If no scheme is provided, `https` is assumed.\n* An HTTP GET on the URL must yield a [google.protobuf.Type][]\n  value in binary format, or produce an error.\n* Applications are allowed to cache lookup results based on the\n  URL, or have them precompiled into a binary to avoid any\n  lookup. Therefore, binary compatibility needs to be preserved\n  on changes to types. (Use versioned type names to manage\n  breaking changes.)\n\nNote: this functionality is not currently available in the official\nprotobuf release, and it is not used for type URLs beginning with\ntype.googleapis.com.\n\nSchemes other than `http`, `https` (or the empty scheme) might be\nused with implementation specific semantics."
        },
        "value": {
          "type": "string",
          "format": "byte",
          "description": "Must be a valid serialized protocol buffer of the above specified type."
        }
      },
      "description": "`Any` contains an arbitrary serialized protocol buffer message along with a\nURL that describes the type of the serialized message.\n\nProtobuf library provides support to pack/unpack Any values in the form\nof utility functions or additional generated methods of the Any type.\n\nExample 1: Pack and unpack a message in C++.\n\n    Foo foo = ...;\n    Any any;\n    any.PackFrom(foo);\n    ...\n    if (any.UnpackTo(\u0026foo)) {\n      ...\n    }\n\nExample 2: Pack and unpack a message in Java.\n\n    Foo foo = ...;\n    Any any = Any.pack(foo);\n    ...\n    if (any.is(Foo.class)) {\n      foo = any.unpack(Foo.class);\n    }\n\n Example 3: Pack and unpack a message in Python.\n\n    foo = Foo(...)\n    any = Any()\n    any.Pack(foo)\n    ...\n    if any.Is(Foo.DESCRIPTOR):\n      any.Unpack(foo)\n      ...\n\n Example 4: Pack and unpack a message in Go\n\n     foo := \u0026pb.Foo{...}\n     any, err := anypb.New(foo)\n     if err != nil {\n       ...\n     }\n     ...\n     foo := \u0026pb.Foo{}\n     if err := any.UnmarshalTo(foo); err != nil {\n       ...\n     }\n\nThe pack methods provided by protobuf library will by default use\n'type.googleapis.com/full.type.name' as the type URL and the unpack\nmethods only use the fully qualified type name after the last '/'\nin the type URL, for example \"foo.bar.com/x/y.z\" will yield type\nname \"y.z\".\n\n\nJSON\n====\nThe JSON representation of an `Any` value uses the regular\nrepresentation of the deserialized, embedded message, with an\nadditional field `@type` which contains the type URL. Example:\n\n    package google.profile;\n    message Person {\n      string first_name = 1;\n      string last_name = 2;\n    }\n\n    {\n      \"@type\": \"type.googleapis.com/google.profile.Person\",\n      \"firstName\": \u003cstring\u003e,\n      \"lastName\": \u003cstring\u003e\n    }\n\nIf the embedded message type is well-known and has a custom JSON\nrepresentation, that representation will be embedded adding a field\n`value` which holds the custom JSON in addition to the `@type`\nfield. Example (for message [google.protobuf.Duration][]):\n\n    {\n      \"@type\": \"type.googleapis.com/google.protobuf.Duration\",\n      \"value\": \"1.212s\"\n    }"
    }
...
}
```

## Expected behavior

The `typeUrl` field within `protobufAny` should be `@type`.

## Actual Behavior

The `@type` field is missing.

## Your Environment

Go 1.16
Windows 10
I'm not sure how to find out the version of protoc-gen-openapiv2 I'm using, but this is a new project today so I'm guessing up-to-date.

### PR DESCRIPTION
**Pull request by dan-j**
#### References to other Issues or PRs

Fixes #2177

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?

Yes

#### Brief description of what is fixed or changed

Output the correct JSON schema for `google.protobuf.Any` as specified by the [any.proto documentation](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/any.proto).

#### Other comments

Originally created PR #2180 but this wasn't the best approach. I've closed that and opened this since it made reviewing on top of out-of-date comments difficult.

I've made three separate commits which may make reviewing easier. I've added tests as the first commit which reproduces the issue.

### CODE REVIEW

**Comment by dan-j** [comment]
Just to help the reviewer, the only files I've changed is `template.go` and `template_test.go`. The rest of the changes are generated by `make generate` and `bazel`

**Review by johanbrandhorst — APPROVED** [review]
This is a great change, thank you for your thorough testing and your patience!

**Comment by johanbrandhorst** [comment]
@googlebot I consent.

**Comment by johanbrandhorst** [comment]
Just made a quick fix to the formatting of the test file :)

**Comment by johanbrandhorst** [comment]
Thanks for your contribution!

**Pull request merged**
