### PR TITLE
feat: add enumAsInts flag

### LINKED ISSUE #1177: protoc-gen-swagger: support outputting enum parameters as integers
grpc gateway support EnumsAsInts, however grpc swagger has not this option

### PR DESCRIPTION
**Pull request by rowe0x**
fix #1177

### CODE REVIEW

**Comment by rowe0x** [comment]
@johanbrandhorst resolved :）

**Comment by nashikb** [comment]
@johanbrandhorst @rowe0x The enums are generated with an array of strings rather than an array of ints, which down-stream breaks swagger generators. Was this really the expected behavior?

**Comment by johanbrandhorst** [comment]
It's an optional flag, if it breaks your generators just don't set it. Or am I misunderstanding something?

**Comment by nashikb** [comment]
Absolutely, it's not an issue in the installed-base sense. But for the optional feature itself, I'm not sure how to use it since it's not a format supported by swagger, or at least by the "standard". I'd love to have enums as ints, and I was pleased to see this land 6 days before I wanted it :-) but the downstream support doesn't seem to be there.

**Comment by johanbrandhorst** [comment]
Ok, I see what you're saying. Regardless, clearly some users wanted it and here we are 🤷‍♂️.

**Pull request merged**
