### PR TITLE
Use status package for error and introduce WithProtoErrorHandler option

### PR DESCRIPTION
**Pull request by kazegusuri**
grpc-go introduced status package to handle errors with concrete types instead of interface and obsoleted some functions like grpc.Errorf.

First, this PR changed code to use status package. This will require grpc-go v1.3+
And, add `WithProtoErrorHandler` option and `ProtoErrorHandlerFunc` for handle errors as `Status` message in grpc-gateway instead of original error type a.k.a `errorBody`.
This also unifies errors returned by gRPC server and errors happened inside grpc-gateway, which helps error handling in client.

I think discussion required for response status of errors inside grpc-gateway and how to handle errors for streaming.
If needed, I will separate this PR into two PRs.

### CODE REVIEW

**Comment by tmc** [comment]
@kazegusuri thanks for this! this looks great. It looks like your generated swagger/openapi is a bit out of date.

**Comment by kazegusuri** [comment]
It was actually caused by using newer version of protoc v3.3.0. I regenerated files with protoc v3.1.0.

**Comment by TamalSaha** [comment]
Hi, we would like to see this pr merged. The new status stuff looks great!

**Comment by kazegusuri** [comment]
ready to be merged if no one opposes the response status.

**Pull request merged**
