### PR TITLE
improve {incoming,outgoing}HeaderMatcher logic

### PR DESCRIPTION
**Pull request by flisky**
* default implementation over nil-check
* really exclude header when outgoingHeaderMatcher returns false

### CODE REVIEW

**Comment by TamalSaha** [comment]
@flisky, can you sign the Google CLA, if you haven't already. PR otherwise looks good to me.

**Comment by flisky** [comment]
Actually, I already contributed. Same slow CLA check last time, and no idea why.

**Comment by flisky** [comment]
ping @TamalSaha

**Comment by TamalSaha** [comment]
pr is LGTM. I will let @tmc / @achew22 to merge it.

**Pull request merged**
