### PR TITLE
Use base64.URLEncoding for []byte parameters in query

### PR DESCRIPTION
**Pull request by tvoll**
Changes encoding method to base64.URLEncoding for query parameters of type []byte.

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Hi, please rebase on `master`, we've changed our generation strategy quite a bit with https://github.com/grpc-ecosystem/grpc-gateway/pull/1971.

**Review by johanbrandhorst — APPROVED** [review]

**Comment by johanbrandhorst** [comment]
Hi, this change looks great to me, thanks for your contribution. Can you please sign the CLA?

**Comment by tvoll** [comment]
@googlebot I signed it!

**Comment by johanbrandhorst** [comment]
Thanks for your contribution!

**Comment by tvoll** [comment]
@johanbrandhorst Thank you for all of your work! I'm still blown away by what you can achieve with gRPC transcoding.

**Pull request merged**
