### PR TITLE
chore: Included githubactions in the dependabot config

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
I think this job is failing because it may not be up-to-date with `master`, please rebase or merge master into your branch.

**Comment by naveensrinivasan** [comment]
> I think this job is failing because it may not be up-to-date with `master`, please rebase or merge master into your branch.

It is done. PTAL. Thanks

**Comment by naveensrinivasan** [comment]
> I think this job is failing because it may not be up-to-date with `master`, please rebase or merge master into your branch.

@johanbrandhorst  A friendly ping to merge this. Thanks

**Comment by naveensrinivasan** [comment]
@johanbrandhorst  A friendly ping.

**Comment by johanbrandhorst** [comment]
Not sure how I missed the pings on this, I apologize profusely. I just went back to look at it and this looks fine. I reopened it to trigger a rerun of our new CI.

**Pull request merged**
