### PR TITLE
Add omit-enum-default-value option to protoc-gen-openapiv2

### LINKED ISSUE #888: Option for omitting zero enum value from generated Swagger
It's pretty typical practice in proto APIs for enum types with no natural default to declare the 0 value as UNKNOWN (or similar). Often UNKNOWN is not a valid option, but is declared to differentiate the "unset" case.

JSON semantics are different: The "unset" case is explicit, because the field is not present in the map object.

Currently, the generated Swagger spec exposes such an "UNKNOWN" option as a legitimate choice, and records it as the default choice. For cases where "UNKNOWN" is *not* a legitimate choice and should not be recorded as such in API docs/generated client code.
  
### Bug reports:

Fill in the following sections with explanations of what's gone wrong.

### Steps you follow to reproduce the error:

Example input:
```
enum Type {
    UNKNOWN = 0;
    FOO = 1;
    BAR = 2;
}
```

Current Swagger type definition output:
```
    "Type": {
      "type": "string",
      "enum": [
        "UNKNOWN",
        "FOO",
        "BAR"
      ],
      "default": "UNKNOWN"
    }
```

### What did you expect to happen instead:

An annotation or other option to emit:

```
    "Type": {
      "type": "string",
      "enum": [
        "FOO",
        "BAR"
      ]
    }
```

### What's your theory on why it isn't working:

Current behavior is the safe default.

An option to adjust this would most likely take the form of a new EnumOption annotation, with boolean field `omit_default` or similar to control this behavior: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-swagger/options/annotations.proto

### PR DESCRIPTION
**Pull request by hiroyoshii**
#### References to other Issues or PRs
Fixes #888 

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?
Yes

#### Brief description of what is fixed or changed
This PR adds a omit-enum-default-value option to protoc-gen-openapiv2/main.go.
If this option is set, zero value of enum type is ommitted from swagger json.

### CODE REVIEW

**Review by adambabik — COMMENTED** [review]
LGTM! Thanks for your contribution!

Please take a look at [the Google CLA status](https://github.com/grpc-ecosystem/grpc-gateway/pull/2480/checks?check_run_id=4687444063). It seems like something is off with regard to your email associated with the CLA and the one used to submit commits in this PR.

**Comment by hiroyoshii** [comment]
@adambabik 
Sorry, I committed with wrong git user. 
I want to recreate PR, so can you close this PR?

**Comment by adambabik** [comment]
@hiroyoshii I can close it or you can force push to your branch with a modified author as described [here](https://stackoverflow.com/a/3042512).

**Comment by hiroyoshii** [comment]
Thanks @adambabik.
I modified commit author and fix a pointed out.

**Review by adambabik — APPROVED** [review]

**Review by johanbrandhorst — CHANGES_REQUESTED** [review]
Hi, thanks for the PR! Could you also add a way to set this option in our Bazel definitions? https://github.com/grpc-ecosystem/grpc-gateway/blob/c52fba18f5ef3b6961c80879bdfdad1b6f5f7334/protoc-gen-openapiv2/defs.bzl#L113

**Comment by hiroyoshii** [comment]
Thanks @johanbrandhorst. I modified a defs.bzl !

**Review by johanbrandhorst — APPROVED** [review]

**Comment by johanbrandhorst** [comment]
Not necessary as part of this PR, but would you be willing to contribute a small docs update for this new setting too?

**Comment by hiroyoshii** [comment]
yes, of course!
Should I modify customizing_openapi_output page?

https://github.com/grpc-ecosystem/grpc-gateway/blob/master/docs/docs/mapping/customizing_openapi_output.md?plain=1#L236

**Comment by hiroyoshii** [comment]
yes, of course!
Should I modify customizing_openapi_output page?

https://github.com/grpc-ecosystem/grpc-gateway/blob/master/docs/docs/mapping/customizing_openapi_output.md

**Comment by johanbrandhorst** [comment]
Yes, that would be perfect

**Pull request merged**
