### PR TITLE
Allowing unknown fields to be dropped instead of returning error from…

### PR DESCRIPTION
**Pull request by sriniven**
… grpc gateway

### CODE REVIEW

**Comment by yugui** [comment]
@sriniven 
Thank you for fixing the issue.
* Could you also fix `jsonpb.UnmarshalNext` in `decodeNonProtoField`?
* github is failing to check if you have signed [a CLA](https://cla.developers.google.com/clas).
   I have asked grpc team about this issue. But could you sign the CLA if you have not yet?

**Comment by zinuga** [comment]
I checked and it shows @sriniven has signed cla

**Comment by yugui** [comment]
LGTM.
@sriniven Thank you for your contribution.
@zinuga Thank you for your help.

**Comment by sriniven** [comment]
Awesome, thanks Yugui.

On Sun, Aug 7, 2016 at 11:56 PM, Yuki Yugui Sonoda <notifications@github.com

**Pull request merged**
