### PR TITLE
reorganize docs; add page for customizing gateway output

### PR DESCRIPTION
**Pull request by ewhauser**
The existing site was a bit hard to navigate with all the pages at the top level. This change provides a better table of content for the docs and adds documentation for `google.api.field_behavior`.

Screen Shot 2020-11-13 at 12 27 22 PM

I'm open to changing any terminology and structure. I don't love the current name for the `Operations` section as it's really "runtime behaviors + observability stuff".

### CODE REVIEW

**Review by johanbrandhorst — APPROVED** [review]
Amazing, can't thank you enough for this!

**Comment by bconway** [comment]
Thank you for all your work here and in #1806, this is great stuff.

I was a little surprised to find that field options did not show up when generating OpenAPI output, when following the instructions on the web site (Tutorial followed by Customizing OpenAPI Output). I then realized that this is not included as part of a release yet (`go get/install` downloads 2.0.1). Should a note be added to the doc regarding availability, or perhaps a new point release is expected in the near future?

Thanks.

**Comment by johanbrandhorst** [comment]
I've just tagged [v2.1.0](https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v2.1.0), thanks for the impetus.

**Comment by bconway** [comment]
Much appreciated!

**Pull request merged**
