### PR TITLE
fix rpc comment generation against allow_merge

### LINKED ISSUE #664: Merging swagger specs fails to use rpc comments
I have two `proto` files:

`a.proto`:
```protobuf
syntax = "proto3";

package api.v1;

import "google/api/annotations.proto";

// A is a service for handling Foo stuff.
service A {
  // List all Foos
  //
  // Returns a (possibly paginated) list of all foo resources on success.
  rpc ListFoos (ListFoosRequest) returns (ListFoosResponse) {
    option (google.api.http) = { get: "/v1/foos" };
  }
}

// The ListFoos request message.
message ListFoosRequest {}

// The ListFoos response message.
message ListFoosResponse {}
```

`b.proto`:
```protobuf
syntax = "proto3";

package api.v1;

import "google/api/annotations.proto";

// B is a service for handling Bar stuff.
service B {
  // List all Bars
  //
  // Returns a (possibly paginated) list of all bar resources on success.
  rpc ListBars (ListBarsRequest) returns (ListBarsResponse) {
    option (google.api.http) = { get: "/v1/bars" };
  }
}

// The ListBars request message.
message ListBarsRequest {}

// The ListBars response message.
message ListBarsResponse {}
```

I tried to create a single swagger spec by using the `allow_merge` option. However, the generator removes some of the protobuf comments which get transformed into the endpoint description.

**Steps you follow to reproduce the error:**

1. Grab the provided protobuf file `a.proto` and `b.proto`
2. Generate the swagger spec **without** merging:
    ```bash
    protoc -I=. \
            -I=$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway \
            -I=$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
            --swagger_out=logtostderr=true:. \
            a.proto b.proto
    ```
3. Generate the swagger spec **with** merging:
    ```bash
    protoc -I=. \
            -I=$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway \
            -I=$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
            --swagger_out=logtostderr=true,allow_merge=true:. \
            a.proto b.proto
    ```

**What did you expect to happen instead:**

Take a look at the separate specifications, the protobuf comments got transformed into endpoint descriptions:

`a.swagger.json`:
```json
{
  "swagger": "2.0",
  "info": {
    "title": "a.proto",
    "version": "version not set"
  },
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/v1/foos": {
      "get": {
        "summary": "List all Foos",
        "description": "Returns a (possibly paginated) list of all foo resources on success.",
        "operationId": "ListFoos",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/v1ListFoosResponse"
            }
          }
        },
        "tags": [
          "A"
        ]
      }
    }
  },
  "definitions": {
    "v1ListFoosResponse": {
      "type": "object",
      "description": "The ListFoos response message."
    }
  }
}
```

`b.swagger.json`:
```json
{
  "swagger": "2.0",
  "info": {
    "title": "b.proto",
    "version": "version not set"
  },
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/v1/bars": {
      "get": {
        "summary": "List all Bars",
        "description": "Returns a (possibly paginated) list of all bar resources on success.",
        "operationId": "ListBars",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/v1ListBarsResponse"
            }
          }
        },
        "tags": [
          "B"
        ]
      }
    }
  },
  "definitions": {
    "v1ListBarsResponse": {
      "type": "object",
      "description": "The ListBars response message."
    }
  }
}
```

This isn't true for the merged specification:

`apidocs.swagger.json`:
```json
{
  "swagger": "2.0",
  "info": {
    "title": "a.proto",
    "version": "version not set"
  },
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/v1/bars": {
      "get": {
        "operationId": "ListBars",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/v1ListBarsResponse"
            }
          }
        },
        "tags": [
          "B"
        ]
      }
    },
    "/v1/foos": {
      "get": {
        "summary": "List all Foos",
        "description": "Returns a (possibly paginated) list of all foo resources on success.",
        "operationId": "ListFoos",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/v1ListFoosResponse"
            }
          }
        },
        "tags": [
          "A"
        ]
      }
    }
  },
  "definitions": {
    "v1ListBarsResponse": {
      "type": "object",
      "description": "The ListBars response message."
    },
    "v1ListFoosResponse": {
      "type": "object",
      "description": "The ListFoos response message."
    }
  }
}
```

This spec misses the description of the `/v1/bars` endpoint.

**What's your theory on why it isn't working:**

There seems to be a bug in the code which merges the two specs. I this its located around here: https://github.com/grpc-ecosystem/grpc-gateway/blob/a5b66c16bab6156b1cc525e76159bdff463123ba/protoc-gen-swagger/genswagger/generator.go#L93-L97

If merged to the leader, the code does not copy the comments.

### PR DESCRIPTION
**Pull request by kentdotn**
#### References to other Issues or PRs

Fixes #664 

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?
Yes

#### Brief description of what is fixed or changed
Currently` protoc-gen-swagger` does not make rpc comments properly when you give `allow_merge=yes` option.
This PR fixes the problem.

For example, here is a diff between ones generated by current `master` and this PR:
```patch
diff --git a/examples/internal/proto/examplepb/swagger_merge.swagger.json b/examples/internal/proto/examplepb/swagger_merge.swagger.json
index b8d4ca0..39e37d5 100644
--- a/examples/internal/proto/examplepb/swagger_merge.swagger.json
+++ b/examples/internal/proto/examplepb/swagger_merge.swagger.json
@@ -82,6 +82,8 @@
     },
     "/v1/example/b/1": {
       "post": {
+        "summary": "ServiceB.MethodOne receives InMessageB and returns OutMessageB",
+        "description": "Here is the detail explanation about ServiceB.MethodOne.",
         "operationId": "ServiceB_MethodOne",
         "responses": {
           "200": {
@@ -114,6 +116,8 @@
     },
     "/v1/example/b/2": {
       "post": {
+        "summary": "ServiceB.MethodTwo receives OutMessageB and returns InMessageB",
+        "description": "Here is the detail explanation about ServiceB.MethodTwo.",
         "operationId": "ServiceB_MethodTwo",
         "responses": {
           "200": {
```

### CODE REVIEW

**Comment by kentdotn** [comment]
@googlebot I signed it!

**Comment by kentdotn** [comment]
> Could you may add an example

In this PR comment? OK, hold on, please.

> Could add two simple files

You mean adding, say,  `a.proto` and `b.proto` under `examples/internal/proto/examplepb` and then add one more target in the Makefile like
```make
SWAGGER_EXAMPLES_MERGE=examples/internal/proto/examplepb/a.proto \
                     examples/internal/proto/examplepb/b.prot
$(EXAMPLE_SWAGGERSRCS_MERGE): $(SWAGGER_PLUGIN) $(SWAGGER_EXAMPLES_MERGE)
        protoc -I $(PROTOC_INC_PATH) -I. -I$(GOOGLEAPIS_DIR) --plugin=$(SWAGGER_PLUGIN) --swagger_out=logtostderr=true,allow_merge=true:. $(SWAGGER_EXAMPLES_MERGE)
```
Or is it suffice simply adding `allow_merge=true` to existing `$(EXAMPLE_SWAGGERSRCS)`?

**Comment by kentdotn** [comment]
Hmm... the patch works for my *.proto files, but it looks it doesn't help some other (rather simple) cases.
I'm digging into it further.

**Comment by johanbrandhorst** [comment]
> > Could you may add an example
> 
> In this PR comment? OK, hold on, please.
> 
> > Could add two simple files
> 
> You mean adding, say, `a.proto` and `b.proto` under `examples/internal/proto/examplepb` and then add one more target in the Makefile like
> 
> ```makefile
> SWAGGER_EXAMPLES_MERGE=examples/internal/proto/examplepb/a.proto \
>                      examples/internal/proto/examplepb/b.prot
> $(EXAMPLE_SWAGGERSRCS_MERGE): $(SWAGGER_PLUGIN) $(SWAGGER_EXAMPLES_MERGE)
>         protoc -I $(PROTOC_INC_PATH) -I. -I$(GOOGLEAPIS_DIR) --plugin=$(SWAGGER_PLUGIN) --swagger_out=logtostderr=true,allow_merge=true:. $(SWAGGER_EXAMPLES_MERGE)
> ```
> 
> Or is it suffice simply adding `allow_merge=true` to existing `$(EXAMPLE_SWAGGERSRCS)`?

Lets add a new example as you suggest. Maybe name them something like `swagger_merge_a.proto` and `swagger_merge_b.proto`?

**Comment by kentdotn** [comment]
Ok, so I figured out what going wrong.
The code I posted solves a bug but there's another one.

The following might solve the other bug but I'm not sure this is no side effect.
```patch
diff --git a/protoc-gen-swagger/genswagger/template.go b/protoc-gen-swagger/genswagger/template.go
index da90927..27a8e76 100644
--- a/protoc-gen-swagger/genswagger/template.go
+++ b/protoc-gen-swagger/genswagger/template.go
@@ -1659,7 +1659,7 @@ func isProtoPathMatches(paths []int32, outerPaths []int32, typeName string, type
                        typeNameDescriptor = reflect.TypeOf((*pbdescriptor.DescriptorProto)(nil))
                }
 
-               if paths[0] != protoPathIndex(typeNameDescriptor, typeName) || paths[1] != typeIndex {
+               if paths[0] != protoPathIndex(typeNameDescriptor, typeName) {
                        return false
                }
                paths = paths[2:]
```

The problem is occurred because `isProtoPathMatches` doesn't care about `typeIndex` for merged target. Perhaps safer way to solve this is to have proper index for each method defined in a same `svc.File`.

What do you think of the snippet above? @johanbrandhorst

**Comment by kentdotn** [comment]
OK, the patch above doesn't work properly if you define two ore more services in one proto file.
Now I'll go the 'safer' way...

**Comment by kentdotn** [comment]
> Could you may add an example

Added in PR comment.

> Could add two simple files

Added.

**Comment by johanbrandhorst** [comment]
Thanks for your contribution! Could you cherry pick this against v2?

**Comment by kentdotn** [comment]
Alright, I'll push another one.

**Pull request merged**
