### PR TITLE
Return codes.InvalidArgument to rather return HTTP 400 instead of HTTP 500

### PR DESCRIPTION
**Pull request by pieterlouw**
Hi,

Currently if there's a conversion error on the request then the gateway return an HTTP 500 with the Go error in the HTTP Body.

Won't it be clearer to the API client user if a `codes.InvalidArgument` (that translate to HTTP 400) is returned rather?

Pieter

### CODE REVIEW

**Comment by achew22** [comment]
Pieter, this seems reasonable to me. Could you sign the CLA and add a test to verify the new behavior?

**Comment by pieterlouw** [comment]
Hi,
I've signed the CLA.

About the test, where exactly should I add one ?
https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/integration_test.go
or
https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/gengateway/template_test.go

**Comment by achew22** [comment]
Generally I believe you should test it in the smallest size test that completely validates behavior. Since template.go is generating a string that is going to be compiled by the go compiler I don't know that we can fully test the functionality in template.go. Therefore, I think the test should go in integration.go. If you have a nifty trick for testing it in template.go I would love to learn.

**Comment by achew22** [comment]
Oh, I should also note that since you're modifying a template you will need to run `make examples` in the root directory to update all the example code with your change.

Thanks!

**Comment by pieterlouw** [comment]
Closing this as #409 have test case and examples

**Pull request closed without merging**
