### PR TITLE
Fix templateToSwaggerPath generates invalid path

### PR DESCRIPTION
**Pull request by ch3rub1m**
Additional PR for #704 to avoid #1000

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Thanks for this fix!

@tlyng Can you confirm this fixes your issue?

**Comment by johanbrandhorst** [comment]
Bump @tlyng, have you tested this fix?

**Comment by johanbrandhorst** [comment]
@ch3rub1m could you rebase this on master please? Lets get this fix merged.

**Comment by ch3rub1m** [comment]
> @ch3rub1m could you rebase this on master please? Lets get this fix merged.

Ok, I'll do it

**Comment by ch3rub1m** [comment]
@johanbrandhorst Have done.

**Comment by johanbrandhorst** [comment]
The online ui is still reporting some conflicts, are you sure you pushed it?

image

**Comment by ch3rub1m** [comment]
@johanbrandhorst finished

**Comment by johanbrandhorst** [comment]
Thanks for your contribution!

**Comment by johanbrandhorst** [comment]
Unfortunately this was causing crashes for valid paths (such as `get: "/api/v3/availabilityGroup/{xid}/parent"`), so I've had to revert this: https://github.com/grpc-ecosystem/grpc-gateway/pull/1078. @ch3rub1m a new issue is being raised with more details, but we'll need a new version of this in.

**Comment by BinaryHexer** [comment]
@johanbrandhorst is a new version of this already merged? Because I am able to reproduce the underlying issue with the latest master.

**Comment by johanbrandhorst** [comment]
No, I don't think it was ever picked up again unfortunately. We'd love to have someone contribute another fix 😄.

**Pull request merged**
