### PR TITLE
add plugin param 'allow_delete_body' 

### PR DESCRIPTION
**Pull request by msample**
Allows  GRPC REST mappings for legacy services that inappropriately use HTTP DELETE with a body
Issue #279

### CODE REVIEW

**Comment by msample** [comment]
I filled in the google contributor license agreement just after I submitted the PR.  Not sure how to make the cla/google check go faster or retry.

**Comment by tmc** [comment]
@msample thank you for your contribution. This code looks good -- what are your thoughts on if this flag should be commented?

**Comment by msample** [comment]
@tmc hopefully most people won't need it, but I'd be happy to update wherever flags are externally documented if you want.  Please point me at right thing to edit.

Alternatively, we could upgrade the error message that is currently printed when you try to use a DELETE with a body to mention this option (gets to be a bit of a drag if we add more cases that care if DELETE has a body though).

**Comment by tmc** [comment]
I'm fine with leaving it undocumented. Other thoughts @achew22, @yugui, @t-yuki?

**Comment by achew22** [comment]
I like it as an undocumented feature. @msample could you add a couple of tests to verify that it does what you need when the flag is set?

**Comment by msample** [comment]
@achew22 sounds good. I'll try to get to it this weekend.

**Comment by msample** [comment]
Two things I left as-is that seem suspect in protoc-gen-swagger/main.go.  Some might depend on this behaviour:

```	if *file != "stdin" {
		f, _ = os.Open("input.txt") // <---" input.txt"? not *file?
	}
```

2. support of pkg map parameters. "Mfoo/bar/baz.proto=github.com/proj/with/gen/baz-pb-go" seems unneeded for generating swagger.  Could break some makefiles if it becomes a  param error tho.

**Comment by tmc** [comment]
@msample that does appear suspect, thanks for pointing that out. Can you comment again to kick googlebot?

**Comment by msample** [comment]
CLA check kick.

**Comment by tmc** [comment]
@msample I like the kvvar refactor but can we separate that into a separate pr?

**Comment by msample** [comment]
@tmc sure, not a problem. Should probably be applied to both protoc_gen_* anyway.

**Comment by msample** [comment]
@tmc kvvar removed.

**Comment by msample** [comment]
last commit under my work email.  Have added CLA to that.

**Comment by tmc** [comment]
@msample thanks!

**Pull request merged**
