### PR TITLE
Added support for more WKT

### PR DESCRIPTION
**Pull request by mayankcpdixit**
Adding support for more well known types.
Adding support for wrappers (_google.protbuf.wrappers_)
Adding Example for using StringValue protobuf wrapper in url template option

Should fix: https://github.com/grpc-ecosystem/grpc-gateway/issues/808

### CODE REVIEW

**Comment by mayankcpdixit** [comment]
@johanbrandhorst Right. Removed those.

**Comment by johanbrandhorst** [comment]
It looks like the generated files don't build, can you see if we can fix the signature of the new functions?

**Comment by johanbrandhorst** [comment]
This is great, thanks! I will merge once the build has finished successfully :).

**Comment by drigz** [comment]
@johanbrandhorst Created #817 to avoid noise on this PR.

**Comment by johanbrandhorst** [comment]
That bazel fix command is really impressive, wow! I'll merge this once the build finishes :).

**Comment by mayankcpdixit** [comment]
> That bazel fix command is really impressive, wow! I'll merge this once the build finishes :).

Agree. It finished smoothly though it took really long. I felt there should be easier way so I don't have to download heavy docker images. Maybe use multistage build. idk. just thinking out loud.

**Comment by johanbrandhorst** [comment]
Thank you for your contribution!

**Comment by mayankcpdixit** [comment]
No problem @johanbrandhorst . I'm using it for one of my work item. So I had to make it work anyway.

**Pull request merged**
