### PR TITLE
fix 2 typos in Registry.SetPrefix's comment

### PR DESCRIPTION
**Pull request by hectorj**

### CODE REVIEW

**Comment by achew22** [comment]
@hectorj, Have you filled out the Google CLA?

**Comment by hectorj** [comment]
I thought I had in the past, and I just signed it again to be sure. I don't know what the cla bot is doing.

**Comment by tmc** [comment]
Thanks for your contribution! master has a build system fix, can you please rebase this?

**Comment by hectorj** [comment]
Done :slightly_smiling_face:

**Pull request merged**
