### PR TITLE
protoc-gen-openapiv2: RPC visibility setting transitively applied to messages

### PR DESCRIPTION
**Pull request by erademacher**
References to other Issues or PRs
Fixes https://github.com/grpc-ecosystem/grpc-gateway/issues/2691

Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md?rgh-link-date=2022-08-31T00%3A12%3A15Z)?
Yes!

Brief description of what is fixed or changed
Skip hidden methods in findServicesMessagesAndEnumerations, transitively hiding their requests and responses unless they're included in another visible method.

Other comments
Redoing #2868.

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Looks like we got a formatter diff 😁: https://github.com/grpc-ecosystem/grpc-gateway/runs/8260415681?check_suite_focus=true

**Comment by erademacher** [comment]
Of course there's a formatter diff... Hang on.

**Review by johanbrandhorst — APPROVED** [review]
LGTM

**Comment by johanbrandhorst** [comment]
Thank you for your contribution!

**Comment by erademacher** [comment]
Thanks for being patient with me!

**Pull request merged**
