### PR TITLE
Added camelCase example

### PR DESCRIPTION
**Pull request by srikrsna**

### CODE REVIEW

**Comment by srikrsna** [comment]
#334

**Comment by srikrsna** [comment]
@achew22 How can changing docs break the build?

**Comment by achew22** [comment]
I'm not sure. I'm going to retrigger the CI to run. I'm thinking there was probably a transitive outage at one of the hosting sites for our dependencies.

**Comment by johanbrandhorst** [comment]
@srikrsna Please rebase this, we had some CI instability during the time you submitted this. Looks like a good change to me!

**Pull request closed without merging**
