### PR TITLE
fix rpc comment generation against allow_merge (v2)

### PR DESCRIPTION
**Pull request by kentdotn**
#### References to other Issues or PRs

Same as #1445 but for v2

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?
Yes

#### Brief description of what is fixed or changed
See #1445 for details.

### CODE REVIEW

**Comment by kentdotn** [comment]
Hmm, I don't know what causes such diff in `BUILD.bazel`. 
Should I do something?

**Comment by johanbrandhorst** [comment]
> Hmm, I don't know what causes such diff in `BUILD.bazel`.
> Should I do something?

I'm looking into it

**Comment by johanbrandhorst** [comment]
Thanks for your contribution!

**Comment by kentdotn** [comment]
Thanks!

**Pull request merged**
