### PR TITLE
Use io/os instread of ioutil and use suitable verb

### PR DESCRIPTION
**Pull request by sashamelentyev**
io/ioutil have deprecated funcs, use actual funcs

### CODE REVIEW

**Review by johanbrandhorst — APPROVED** [review]
LGTM

**Comment by johanbrandhorst** [comment]
Looks like at least one of the files need to be formatted with `goimports`.

**Comment by sashamelentyev** [comment]
@johanbrandhorst fixed

**Comment by johanbrandhorst** [comment]
Thanks for your contribution!

**Pull request merged**
