### PR TITLE
support allow_delete_body for protoc-gen-grpc-gateway

### PR DESCRIPTION
**Pull request by flisky**
this fixes up #280

### CODE REVIEW

**Comment by tmc** [comment]
@flisky thanks for your fixup!

**Comment by tmc** [comment]
@flisky can you comment again to trigger googlebot?

**Comment by flisky** [comment]
Googlebot seems dead. I've signed the google individual cla, just FYI.

**Comment by flisky** [comment]
ping @tmc

**Comment by zeiler** [comment]
We're blocked by this as well. Any updates?

**Comment by tmc** [comment]
@zeiler @flisky sorry about the delay. This was overlooked. Merged.

**Pull request merged**
