### PR TITLE
Switch from aliased field_mask package to canonical package

### PR DESCRIPTION
**Pull request by liggitt**
#### References to other Issues or PRs

xref https://github.com/kubernetes/kubernetes/issues/113366

#### Brief description of what is fixed or changed

This switches to the canonical fieldmask known type package to help in simplifying genproto references

### CODE REVIEW

**Review by johanbrandhorst — APPROVED** [review]
LGTM

**Comment by johanbrandhorst** [comment]
Looks like you'll need to regenerate the Bazel dependency files, please see CONTRIBUTING.md

**Comment by liggitt** [comment]
ack, missed that, will update

**Comment by johanbrandhorst** [comment]
Thank you for your contribution!

**Pull request merged**
