### PR TITLE
Add method for custom formatting of stream errors.

### PR DESCRIPTION
**Pull request by johanbrandhorst**
Alternative to discussion in https://github.com/grpc-ecosystem/grpc-gateway/issues/538#issuecomment-369139421. This would allow a user to get errors as marshalled `status.Proto()` types with the use of both `WithProtoStreamErrorFormatter` and `WithProtoErrorHandler`.

This is pretty experimental so I'm happy to make any changes.

### CODE REVIEW

**Comment by abursavich** [comment]
I would much prefer the handler's signature to be more in the style of (Default)HTTPError, so that a client can write the stream error however they wish. In my case, I would like to construct my own error status proto directly and avoid my marshalers having to handle maps.

**Comment by johanbrandhorst** [comment]
Could you come up with a practical alternative? The stream is already established at this point, so a handler function may require rewriting of much of the logic.

**Comment by abursavich** [comment]
Here's my first pass. It may need some work: https://github.com/abursavich/grpc-gateway/commit/47b315fad04ce2e68cc41661d2938bcbd643cd41

**Comment by johanbrandhorst** [comment]
@abursavich Thanks for that! I think one problem with your approach is that we expose a new function type, used by the user, which has an empty interface in the signature. That's pretty poor interface design. It also rewrites quite a bit of the logic, and it seems to add an error case if the response is nil, which may break backwards compatibility? I think your suggestion is a step in the right direction, as I would also like more control over the writing of mesages, but maybe the configuration should be more fine grained? One option for formatting the error and one for formatting a successful reply? I'm not sure.

**Comment by abursavich** [comment]
FWIW, the error on nil response was already there, I just lifted it out of streamChunk (which I deleted): https://github.com/grpc-ecosystem/grpc-gateway/blob/cde2f8f5bef06abdf9d0557f284f072f1cfa9f56/runtime/handler.go#L185-L187

I don't like the empty interface much either, but I was matching the existing interface for Marshaler: https://github.com/grpc-ecosystem/grpc-gateway/blob/e4b8a938efae14de11fd97311e873e989896348c/runtime/marshaler.go#L7-L20

**Comment by johanbrandhorst** [comment]
My heart is not really in this change after merging #561, so I will close this to let someone else provide a better solution to the specific problem of customizing stream error returns.

**Pull request closed without merging**
