### PR TITLE
Generate OpenAPI defenitions for messages outside services

### PR DESCRIPTION
**Pull request by sashabaranov**
#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?

Yes.

#### Brief description of what is fixed or changed

Currently, protoc-gen-openapiv2 does not generate OpenAPI definitions for messages which are neither service's requests or responses. This PR fixes that.

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Hi, this looks interesting, could you please add some more explicit tests? Maybe copy paste one of the existing ones and redefine it to include a single message that is not part of any RPC, and check that it gets populated?

**Comment by johanbrandhorst** [comment]
I closed and reopened to trigger the CI run.

**Comment by sashabaranov** [comment]
Ok, I'll add more explicit tests and fix CircleCI one

**Comment by sashabaranov** [comment]
@johanbrandhorst added explicit test, but I'm unsure what to do with CircleCI — it outputs dauntingly big diff, should I just `git add` all the things?

**Comment by johanbrandhorst** [comment]
https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md#i-want-to-regenerate-the-files-after-making-changes details how to regenerate the files after a change you've made. That should match what CI does, and you should check that it didn't produce any change you didn't expect.

**Pull request closed without merging**
