### PR TITLE
Replace	"github.com/ghodss/yaml" with "sigs.k8s.io/yaml"

### LINKED ISSUE #2427: Replace abandoned ghodss/yaml with supported sigs.k8s.io/yaml package
## 🚀 Feature

This package still relies on the (long) abandoned [`ghodss/yaml`](https://pkg.go.dev/github.com/ghodss/yaml) package. The kubernetes maintainers have created a maintained fork of that package ([`sigs.k8s.io/yaml`](https://pkg.go.dev/sigs.k8s.io/yaml)).

Switching to a maintained/supported package would make bug fixes and dependency updates available to this package, and its consumers as well.

### PR DESCRIPTION
**Pull request by slntopp**
#### References to other Issues or PRs

Fixes #2427 

#### Brief description of what is fixed or changed

As @numbsafari mentioned, `sigs.k8s.io/yaml` is quite the trusted fork of `github.com/ghodss/yaml`, so it's fully compatible

#### Other comments

Further help needed with Bazel. `repositories.bzl` still contains `github.com/ghodss/yaml`. Unfortunately I'm not familiar with Bazel, so I can't do anything about it and don't know if leaving it would break anything.

I ran tests as it's configured in CI checks(uncovered files skipped):

```shell
➜ go test -race -coverprofile=coverage.txt ./...                              
ok      github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/integration 1.681s  coverage: [no statements]
ok      github.com/grpc-ecosystem/grpc-gateway/v2/internal/codegenerator        0.734s  coverage: 63.6% of statements
ok      github.com/grpc-ecosystem/grpc-gateway/v2/internal/descriptor   1.267s  coverage: 61.3% of statements
ok      github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule     0.652s  coverage: 91.8% of statements
ok      github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway       0.612s  coverage: 13.8% of statements
ok      github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway/internal/gengateway   1.069s  coverage: 70.1% of statements
ok      github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2  1.440s  coverage: 24.6% of statements
ok      github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/internal/genopenapi      1.394s  coverage: 66.7% of statements
ok      github.com/grpc-ecosystem/grpc-gateway/v2/runtime       1.471s  coverage: 66.3% of statements
ok      github.com/grpc-ecosystem/grpc-gateway/v2/utilities     1.271s  coverage: 90.6% of statements
```

I installed packages I've needed locally:

```shell
➜ go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway                       
➜ go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2  
```

Which worked to me exactly as I needed(but generates gateway code with `github.com/grpc-ecosystem/grpc-gateway/v2/runtime`.

If one tries to install v2/protoc-gen-grpc-gateway and/or v2/protoc-gen-openapiv2, `go install` currently throws:

```
../../go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.7.0/internal/descriptor/grpc_api_configuration.go:8:2: missing go.sum entry for module providing package github.com/ghodss/yaml (imported by github.com/grpc-ecosystem/grpc-gateway/v2/internal/descriptor); to add:
        go get github.com/grpc-ecosystem/grpc-gateway/v2/internal/descriptor@v2.7.0
```

Thanks for your attention!

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
The goreleaser failure is my fault, forgot to update it after last release, will be fixed by #2437. The other failures look like they're the result of not running all the regeneration scripts, check out https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md#i-want-to-regenerate-the-files-after-making-changes for the steps. Finally, you'll need to sign the CLA for us to be able to merge this.

**Comment by slntopp** [comment]
Hi, updated with regeneration scripts artefacts.

**Comment by johanbrandhorst** [comment]
> Hi, updated with regeneration scripts artefacts.

Great, thanks! It looks like you still need to [sign the CLA](https://cla.developers.google.com/) for me to be able to accept this contribution. Also I think you will need to merge/rebase on master to fix the `gorelease` job.

**Comment by slntopp** [comment]
Just signed CLA.

Regarding gorelease, would that work if I just add(cherry-pick() your last commit into my branch?

**Comment by johanbrandhorst** [comment]
Yes, that should also work!

**Comment by johanbrandhorst** [comment]
Can you trigger the CLA bot to check again by replying with:
```
@googlebot I fixed it.
```

**Comment by slntopp** [comment]
@googlebot I fixed it.

**Comment by slntopp** [comment]
All done 👌🏻

**Review by johanbrandhorst — APPROVED** [review]
LGTM

**Comment by johanbrandhorst** [comment]
Thanks a lot for your contribution!

**Pull request merged**
