### PR TITLE
Configure response content type at the method level

### PR DESCRIPTION
**Pull request by nboukeffa**
This PR will add the possibility to configure the response content
type at the method level.

To do such the developer will have to set the `produces` property
like in the following example.

```
rpc OverwriteResponseContentType(google.protobuf.Empty) returns (google.protobuf.StringValue) {
	option (google.api.http) = {
		get: "/v2/example/overwriteresponsecontenttype"
	};
	option (grpc.gateway.protoc_gen_swagger.options.openapiv2_operation) = {
		produces: "application/text"
	};
}
```

### CODE REVIEW

**Comment by nboukeffa** [comment]
@googlebot I signed it!

**Comment by nboukeffa** [comment]
I'm not sure why the build is failing on Circle CI. It's passing locally. If someone can help...

**Comment by johanbrandhorst** [comment]
The bazel failure should be fixed by running:
```bash
$ docker run -itv $(pwd):/grpc-gateway -w /grpc-gateway --entrypoint /bin/bash --rm \
    l.gcr.io/google/bazel -c 'bazel run :gazelle'
```
From https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md

**Comment by johanbrandhorst** [comment]
Thanks for your contribution!

**Comment by nboukeffa** [comment]
All green. You were right the import was missing in the build definition. Your command did the trick.

Maybe adding it to the `CONTRIBUTING.md` could help.

**Pull request merged**
