### PR TITLE
allow path param in client streaming for swagger

### PR DESCRIPTION
**Pull request by vtolstov**
allow using path parameters in client streaming for swagger
generation.

Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

### CODE REVIEW

**Comment by vtolstov** [comment]
thanks, add example to a_bit_of_everything ?

**Comment by johanbrandhorst** [comment]
> thanks, add example to a_bit_of_everything ?

Maybe we can reuse this one? https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/stream.proto#L23-L28

**Comment by vtolstov** [comment]
yeah, looks good. can you provide needed steps?

**Comment by johanbrandhorst** [comment]
> yeah, looks good. can you provide needed steps?

Just add a path parameter and run the regeneration scripts: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md

**Comment by vtolstov** [comment]
then i'm run docker commands i get error 
```
runtime: mlock of signal stack failed: 12
runtime: increase the mlock limit (ulimit -l) or
runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
fatal error: mlock failed
```

but i can't update host kernel now =(

**Comment by johanbrandhorst** [comment]
> then i'm run docker commands i get error
> 
> ```
> runtime: mlock of signal stack failed: 12
> runtime: increase the mlock limit (ulimit -l) or
> runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
> fatal error: mlock failed
> ```
> 
> but i can't update host kernel now =(

Wow, I don't think we've ever had a contributor who _cant_ run docker 😂. I dunno, that's a weird error. You can try to reproduce the build environment locally and regenerate using the makefile.

**Comment by vtolstov** [comment]
error comes from go 1.14. now i'm regen all the stuff and push.
what can you say?

**Comment by johanbrandhorst** [comment]
I can check out your code and regenerate the files myself.

**Comment by johanbrandhorst** [comment]
> I can check out your code and regenerate the files myself.

Looks like you managed to generate them, now you just need to fix the tests.

**Comment by johanbrandhorst** [comment]
Hi Vasiliy, are you still planning on merging this?

**Comment by vtolstov** [comment]
yes, sorry for delay.

**Pull request closed without merging**
