### PR TITLE
go.mod: update grpc from v1.16.0 to v1.17.0

### PR DESCRIPTION
**Pull request by klim0v**
Update the grpc dependency to v1.17.0, which includes the fix
to remove the invalid github.com/golang/lint module requirement
in [grpc/grpc-go#2393](https://github.com/grpc/grpc-go/pull/2393).

This change was generated by running the following commands
using Go 1.11:

```
go get google.golang.org/grpc@v1.17.0
go mod tidy
```

### CODE REVIEW

**Comment by klim0v** [comment]
I signed it!

**Comment by klim0v** [comment]
I signed it!

**Comment by klim0v** [comment]
I signed it!

**Comment by klim0v** [comment]
I signed it!

**Comment by klim0v** [comment]
I signed it!

**Comment by johanbrandhorst** [comment]
The gRPC project recently released 1.19.0 - why not go all the way? Could you try updating to 1.19.0 and see if we get any errors?

**Comment by klim0v** [comment]
> Could you try updating to 1.19.0 and see if we get any errors?
Yes, I'll do it

**Comment by klim0v** [comment]
It's work

**Comment by johanbrandhorst** [comment]
Nice, thanks! I'll just need to confirm with @achew22 that this is still correct in Bazel land before merging.

**Comment by achew22** [comment]
grpc is a dependency that gets managed by `rules_go` so this is good to go. Thanks so much for the PR!

**Pull request merged**
