### PR TITLE
protoc-gen-swagger primitive types in json_schema.type rendering policy

### PR DESCRIPTION
**Pull request by askurydzin**
This PR (preliminary) is an approach to bring a meaning into a json_schema type field definition. The rationale for it is following: if we don't want to expose some internal structure of the message that stands behind some field, we should not provide these details with swagger schema. Also it can be used to solve some corner cases like recursive message definitions via oneof where message itself is only a string on API side and somewhat tree-like on gRPC side. I

So the main features included:

  * protoc-gen-swagger will not render message that has primitive type or references a primitive type (STRING, INT, BOOLEAN, ...)

  * however, it will render message as a definition iff it's included as Request or Response in rpc.

  * example, that include MimicObjectResponse, MimicObjectRequest that are rendered because they are used as response and request messages accordingly, and MimicObjectHidden that is rendered as a string parameter with appropriate Marshal/UnmarshalJSONPB methods to work with it.

```
$ curl -X POST  http://localhost:8080/v1/example/a_bit_of_everything -d '{"mimic_string": "gggggg/  yzzzz/VALUE_ONE"}' | jq

{
  "uuid": "8a90c65f9ff27636c62bde644a7db0aff6f7de715d90b401",
  "mimic_string": "gggggg/yzzzz/VALUE_ONE"
}
```

### CODE REVIEW

**Comment by askurydzin** [comment]
#446

**Comment by johanbrandhorst** [comment]
Thanks for this PR @askurydzin, this is really cool and clever! However, is this a breaking change? Should we consider this for v2?

**Comment by askurydzin** [comment]
Thanks, @johanbrandhorst. I would not consider this as a breaking change, as it employs nonsense combination of options (type "string" for message) that was unlikely used by anyone.

**Comment by johanbrandhorst** [comment]
@askurydzin Terribly sorry, looks like we need another rebase and regenerating of the files :(. I'll get it merged as soon as CI passes again.

**Comment by johanbrandhorst** [comment]
Please rebase on master for new CI functionality.

**Pull request closed without merging**
