### PR TITLE
fix: set consumes definition per operation

### LINKED ISSUE #726: Cannot set `consumes` definition per operation
# Please follow the general troubleshooting steps first:

- [x] Update your protoc to the [latest version](https://github.com/google/protobuf/releases) 
- [x] Update your copy of `grpc-gateway` to the latest version from github. with 
  `git fetch https://github.com/grpc-ecosystem/grpc-gateway master && git reset --hard FETCH_HEAD`
- [x] Delete the `protoc-gen-grpc-gateway` and `protoc-gen-swagger` binary from your `PATH`,
  and install locally built binaries.

### Bug reports:

Cannot set `consumes` definition per operation, even though the `consumes` field is present in the `openapiv2_operation` message  definition. This leads to problem with using the generated swagger spec to generate test server or client for non GRPC clients.

Steps you follow to reproduce the error:

1. Set `consumes` via `openapiv2_swagger` 
2. Set `consumes` via `openapiv2_operation` for a seperate rpc method

What did you expect to happen instead:

1. The consumes option should overwrite the global one, but its not

What's your theory on why it isn't working:

Looking at [this](https://github.com/grpc-ecosystem/grpc-gateway/blob/de0b679b7b2e83123304a21180e92b10b52f4f7c/protoc-gen-swagger/genswagger/template.go#L779) it seems the per operation `consumes` is not being considered

### PR DESCRIPTION
**Pull request by stomy13**
#### References to other Issues or PRs
Fixes #726

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?
Yes

#### Brief description of what is fixed or changed
Cannot set `consumes` definition per operation.

Changed below:
- Added `Consumes` field to `openapiOperationObject`.
- Copy `consumes` if `consumes` definition per operation existed
- There is a similar test, so I added fields into the test to verify.

#### Other comments
This PR is my first contributing in all my life.

### CODE REVIEW

**Review by johanbrandhorst — CHANGES_REQUESTED** [review]
Hi @stomy13, thank you so much for choosing to contribute to our little project! This looks great, I'm just wondering if we could also add an example of multiple `consumes` definitions to one of our example protos, maybe somewhere in here: https://github.com/grpc-ecosystem/grpc-gateway/blob/1b7515f8ec8fb382cc26ba24abf078578ab8c427/examples/internal/proto/examplepb/a_bit_of_everything.proto? That way, we have a practical example of how to use this feature too.

**Comment by stomy13** [comment]
Hi @johanbrandhorst, I added an example, and generated files. Please check.

**Review by johanbrandhorst — APPROVED** [review]
LGTM

**Comment by johanbrandhorst** [comment]
Thanks for your contribution!

**Pull request merged**
