### PR TITLE
Improve comments, fix indentation and add new line

### PR DESCRIPTION
**Pull request by amanjain97**
## WHAT
1. Fix comment grammar in .circleci/config.yml

### CODE REVIEW

**Comment by amanjain97** [comment]
Can anyone help why the generate build is failing when I add a new line

**Comment by johanbrandhorst** [comment]
> Can anyone help why the generate build is failing when I add a new line

Hi Aman, this is a generated file, so you don't want to change it because when we regenerate it later it would show a strange diff. Please revert that part of the PR.

**Comment by amanjain97** [comment]
Hi @johanbrandhorst, I have reverted the changes. Thanks

**Comment by johanbrandhorst** [comment]
Thanks for your contribution! Could you cherry pick this against the v2 branch please?

**Comment by amanjain97** [comment]
@johanbrandhorst, Do we always make two PRs, or should I only make PR for the v2 branch ?

**Comment by johanbrandhorst** [comment]
We need two PRs every time :). We haven't got a better system at the moment, since both branches need CLA approval.

**Pull request merged**
