### PR TITLE
Add a ## Docs section to highlight the docs URL

### PR DESCRIPTION
**Pull request by VinGarcia**
#### References to other Issues or PRs

As suggested on issue grpc-ecosystem/grpc-gateway#1882
I am creating this PR to make the link to the documentation site 
more visible on the README file.

#### Brief description of what is fixed or changed

Add a `### Docs` section to the README file.

#### Other comments

It was also suggested that I created a `### Customizing your gateway` section to the README, but I don't feel qualified yet for writing this section, so I just created this first one.

It is also worth noting that the docs already have a `Customizing your gateway` section which will be very helpful if more people find this page.

### CODE REVIEW

**Review by johanbrandhorst — APPROVED** [review]
LGTM

**Comment by johanbrandhorst** [comment]
Could you please sign the CLA and reply to the bot?

**Comment by VinGarcia** [comment]
@googlebot I signed it!

**Comment by VinGarcia** [comment]
Done @johanbrandhorst, is there anything else?

**Comment by johanbrandhorst** [comment]
Nah, that was it! The fuzzit job has started failing occasionally, unfortunately. I reran it once, but it was still unhappy so we'll just leave it. Thanks for your contribution 😄.

**Pull request merged**
