### PR TITLE
docs: change godoc.org links to pkg.go.dev

### PR DESCRIPTION
**Pull request by johanbrandhorst**
Cherry picked from https://github.com/grpc-ecosystem/grpc-gateway/commit/f4db4a3259acbb6bf3aa1a1520842fc21d00cb27

### CODE REVIEW

**Comment by AyushG3112** [comment]
@googlebot I consent.

**Comment by johanbrandhorst** [comment]
@AyushG3112 could you please give your consent for me to cherry pick this into v2?

**Comment by AyushG3112** [comment]
@johanbrandhorst Already done. ^^

**Comment by AyushG3112** [comment]
@johanbrandhorst I was checking out the PR, and noticed only 1 of the 3 fixes have been cherry picked. Is that intentional?

**Comment by johanbrandhorst** [comment]
> @johanbrandhorst I was checking out the PR, and noticed only 1 of the 3 fixes have been cherry picked. Is that intentional or was something missed? Just confirming.

Ugh I really should've squashed that PR. No, I wanted to cherry pick all of them. Could you open a PR against v2?

**Pull request merged**
